/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.KeyValuesDTO;
import org.openapitools.client.model.LogEntryListResponseDTO;
import org.openapitools.client.model.ServiceDefinitionRequestDTO;
import org.openapitools.client.model.ServiceDefinitionResponseDTO;
import org.openapitools.client.model.ServiceDefinitionsListResponseDTO;
import org.openapitools.client.model.ServiceInterfaceRequestDTO;
import org.openapitools.client.model.ServiceInterfaceResponseDTO;
import org.openapitools.client.model.ServiceInterfacesListResponseDTO;
import org.openapitools.client.model.ServiceQueryFormDTO;
import org.openapitools.client.model.ServiceQueryFormListDTO;
import org.openapitools.client.model.ServiceQueryResultDTO;
import org.openapitools.client.model.ServiceRegistryGroupedResponseDTO;
import org.openapitools.client.model.ServiceRegistryListResponseDTO;
import org.openapitools.client.model.ServiceRegistryRequestDTO;
import org.openapitools.client.model.ServiceRegistryResponseDTO;
import org.openapitools.client.model.SystemListResponseDTO;
import org.openapitools.client.model.SystemRequestDTO;
import org.openapitools.client.model.SystemResponseDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AllApi
 */
@Disabled
public class AllApiTest {

    private final AllApi api = new AllApi();

    /**
     * Return created service definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addServiceDefinitionUsingPOST_0Test() throws ApiException {
        ServiceDefinitionRequestDTO serviceDefinitionRequestDTO = null;
        ServiceDefinitionResponseDTO response = api.addServiceDefinitionUsingPOST_0(serviceDefinitionRequestDTO);
        // TODO: test validations
    }

    /**
     * Return created service interface
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addServiceInterfaceUsingPOST_0Test() throws ApiException {
        ServiceInterfaceRequestDTO serviceInterfaceRequestDTO = null;
        ServiceInterfaceResponseDTO response = api.addServiceInterfaceUsingPOST_0(serviceInterfaceRequestDTO);
        // TODO: test validations
    }

    /**
     * Registers a service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addServiceRegistryUsingPOST_0Test() throws ApiException {
        ServiceRegistryRequestDTO request = null;
        ServiceRegistryResponseDTO response = api.addServiceRegistryUsingPOST_0(request);
        // TODO: test validations
    }

    /**
     * Return created system 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addSystemUsingPOST_0Test() throws ApiException {
        SystemRequestDTO request = null;
        SystemResponseDTO response = api.addSystemUsingPOST_0(request);
        // TODO: test validations
    }

    /**
     * Return an echo message with the purpose of testing the core service availability
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void echoServiceUsingGET_0Test() throws ApiException {
        String response = api.echoServiceUsingGET_0();
        // TODO: test validations
    }

    /**
     * Return requested log entries by the given parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLogEntriesUsingGET_0Test() throws ApiException {
        String direction = null;
        String from = null;
        Integer itemPerPage = null;
        String level = null;
        String logger = null;
        Integer page = null;
        String sortField = null;
        String to = null;
        LogEntryListResponseDTO response = api.getLogEntriesUsingGET_0(direction, from, itemPerPage, level, logger, page, sortField, to);
        // TODO: test validations
    }

    /**
     * Return requested service definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceDefinitionByIdUsingGET_0Test() throws ApiException {
        Long id = null;
        ServiceDefinitionResponseDTO response = api.getServiceDefinitionByIdUsingGET_0(id);
        // TODO: test validations
    }

    /**
     * Return requested service definitions by the given parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceDefinitionsUsingGET_0Test() throws ApiException {
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        ServiceDefinitionsListResponseDTO response = api.getServiceDefinitionsUsingGET_0(direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Return requested service interface
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceInterfaceByIdUsingGET_0Test() throws ApiException {
        Long id = null;
        ServiceInterfaceResponseDTO response = api.getServiceInterfaceByIdUsingGET_0(id);
        // TODO: test validations
    }

    /**
     * Return requested service interfaces by the given parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceInterfacesUsingGET_0Test() throws ApiException {
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        ServiceInterfacesListResponseDTO response = api.getServiceInterfacesUsingGET_0(direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Return requested service registry entries by service definition based on the given parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryEntriesByServiceDefinitionUsingGET_0Test() throws ApiException {
        String serviceDefinition = null;
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        ServiceRegistryListResponseDTO response = api.getServiceRegistryEntriesByServiceDefinitionUsingGET_0(serviceDefinition, direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Return service registry entries by system id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryEntriesBySystemIdUsingGET_0Test() throws ApiException {
        Long id = null;
        ServiceRegistryListResponseDTO response = api.getServiceRegistryEntriesBySystemIdUsingGET_0(id);
        // TODO: test validations
    }

    /**
     * Return all service registry entries
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryEntriesUsingGET1_0Test() throws ApiException {
        ServiceRegistryListResponseDTO response = api.getServiceRegistryEntriesUsingGET1_0();
        // TODO: test validations
    }

    /**
     * Return requested service registry entries by the given parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryEntriesUsingGET_0Test() throws ApiException {
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        ServiceRegistryListResponseDTO response = api.getServiceRegistryEntriesUsingGET_0(direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Return requested service registry entry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryEntryByIdUsingGET_0Test() throws ApiException {
        Long id = null;
        ServiceRegistryResponseDTO response = api.getServiceRegistryEntryByIdUsingGET_0(id);
        // TODO: test validations
    }

    /**
     * Return all service registry entries grouped for frontend usage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryGroupedDataUsingGET_0Test() throws ApiException {
        ServiceRegistryGroupedResponseDTO response = api.getServiceRegistryGroupedDataUsingGET_0();
        // TODO: test validations
    }

    /**
     * Return system by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSystemByIdUsingGET_0Test() throws ApiException {
        Long id = null;
        SystemResponseDTO response = api.getSystemByIdUsingGET_0(id);
        // TODO: test validations
    }

    /**
     * Return systems by request parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSystemsUsingGET_0Test() throws ApiException {
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        SystemListResponseDTO response = api.getSystemsUsingGET_0(direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Merge/Patch a service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void mergeServiceRegistryUsingPATCH_0Test() throws ApiException {
        Long id = null;
        ServiceRegistryRequestDTO request = null;
        ServiceRegistryResponseDTO response = api.mergeServiceRegistryUsingPATCH_0(id, request);
        // TODO: test validations
    }

    /**
     * Return system  updated by fields
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void mergeSystemUsingPATCH_0Test() throws ApiException {
        Long id = null;
        SystemRequestDTO request = null;
        SystemResponseDTO response = api.mergeSystemUsingPATCH_0(id, request);
        // TODO: test validations
    }

    /**
     * Return Service Registry data that fits the specification
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void multiQueryRegistryUsingPOST_0Test() throws ApiException {
        ServiceQueryFormListDTO forms = null;
        ServiceQueryResultDTO response = api.multiQueryRegistryUsingPOST_0(forms);
        // TODO: test validations
    }

    /**
     * Return updated service definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchUpdateServiceDefinitionUsingPATCH_0Test() throws ApiException {
        Long id = null;
        ServiceDefinitionRequestDTO serviceDefinitionRequestDTO = null;
        ServiceDefinitionResponseDTO response = api.patchUpdateServiceDefinitionUsingPATCH_0(id, serviceDefinitionRequestDTO);
        // TODO: test validations
    }

    /**
     * Return updated service interface
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchUpdateServiceInterfaceUsingPATCH_0Test() throws ApiException {
        Long id = null;
        ServiceInterfaceRequestDTO serviceInterfaceRequestDTO = null;
        ServiceInterfaceResponseDTO response = api.patchUpdateServiceInterfaceUsingPATCH_0(id, serviceInterfaceRequestDTO);
        // TODO: test validations
    }

    /**
     * Return some configuration of ServiceRegistry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pullConfigUsingGET_0Test() throws ApiException {
        KeyValuesDTO response = api.pullConfigUsingGET_0();
        // TODO: test validations
    }

    /**
     * Return systems by request parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pullSystemsUsingGET_0Test() throws ApiException {
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        SystemListResponseDTO response = api.pullSystemsUsingGET_0(direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Return updated service definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putUpdateServiceDefinitionUsingPUT_0Test() throws ApiException {
        Long id = null;
        ServiceDefinitionRequestDTO serviceDefinitionRequestDTO = null;
        ServiceDefinitionResponseDTO response = api.putUpdateServiceDefinitionUsingPUT_0(id, serviceDefinitionRequestDTO);
        // TODO: test validations
    }

    /**
     * Return updated service interface
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putUpdateServiceInterfaceUsingPUT_0Test() throws ApiException {
        Long id = null;
        ServiceInterfaceRequestDTO serviceInterfaceRequestDTO = null;
        ServiceInterfaceResponseDTO response = api.putUpdateServiceInterfaceUsingPUT_0(id, serviceInterfaceRequestDTO);
        // TODO: test validations
    }

    /**
     * Return System by requested dto
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryRegistryBySystemDTOUsingPOST_0Test() throws ApiException {
        SystemRequestDTO request = null;
        SystemResponseDTO response = api.queryRegistryBySystemDTOUsingPOST_0(request);
        // TODO: test validations
    }

    /**
     * Return system by requested id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryRegistryBySystemIdUsingGET_0Test() throws ApiException {
        Long id = null;
        SystemResponseDTO response = api.queryRegistryBySystemIdUsingGET_0(id);
        // TODO: test validations
    }

    /**
     * Return Service Registry data that fits the specification
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryRegistryUsingPOST_0Test() throws ApiException {
        ServiceQueryFormDTO form = null;
        ServiceQueryResultDTO response = api.queryRegistryUsingPOST_0(form);
        // TODO: test validations
    }

    /**
     * Return service registry entries by service definition list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryServiceRegistryEntriesByServiceDefinitionListUsingPOST_0Test() throws ApiException {
        List<String> request = null;
        ServiceRegistryListResponseDTO response = api.queryServiceRegistryEntriesByServiceDefinitionListUsingPOST_0(request);
        // TODO: test validations
    }

    /**
     * Registers a service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerServiceUsingPOST_0Test() throws ApiException {
        ServiceRegistryRequestDTO dto = null;
        ServiceRegistryResponseDTO response = api.registerServiceUsingPOST_0(dto);
        // TODO: test validations
    }

    /**
     * Return created application system 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerSystemUsingPOST_0Test() throws ApiException {
        SystemRequestDTO dto = null;
        SystemResponseDTO response = api.registerSystemUsingPOST_0(dto);
        // TODO: test validations
    }

    /**
     * Remove service definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeServiceDefinitionUsingDELETE_0Test() throws ApiException {
        Long id = null;
        api.removeServiceDefinitionUsingDELETE_0(id);
        // TODO: test validations
    }

    /**
     * Remove service interface
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeServiceInterfaceUsingDELETE_0Test() throws ApiException {
        Long id = null;
        api.removeServiceInterfaceUsingDELETE_0(id);
        // TODO: test validations
    }

    /**
     * Remove the specified service registry entry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeServiceRegistryEntryByIdUsingDELETE_0Test() throws ApiException {
        Long id = null;
        api.removeServiceRegistryEntryByIdUsingDELETE_0(id);
        // TODO: test validations
    }

    /**
     * Remove system
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeSystemUsingDELETE_0Test() throws ApiException {
        Long id = null;
        api.removeSystemUsingDELETE_0(id);
        // TODO: test validations
    }

    /**
     * Remove a registered service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unregisterServiceUsingDELETE_0Test() throws ApiException {
        Integer port = null;
        String serviceDefinition = null;
        String serviceUri = null;
        String systemName = null;
        String address = null;
        api.unregisterServiceUsingDELETE_0(port, serviceDefinition, serviceUri, systemName, address);
        // TODO: test validations
    }

    /**
     * Unregister the given system
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unregisterSystemUsingDELETE_0Test() throws ApiException {
        Integer port = null;
        String systemName = null;
        String address = null;
        api.unregisterSystemUsingDELETE_0(port, systemName, address);
        // TODO: test validations
    }

    /**
     * Update a service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateServiceRegistryUsingPUT_0Test() throws ApiException {
        Long id = null;
        ServiceRegistryRequestDTO request = null;
        ServiceRegistryResponseDTO response = api.updateServiceRegistryUsingPUT_0(id, request);
        // TODO: test validations
    }

    /**
     * Return updated system 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSystemUsingPUT_0Test() throws ApiException {
        Long id = null;
        SystemRequestDTO request = null;
        SystemResponseDTO response = api.updateSystemUsingPUT_0(id, request);
        // TODO: test validations
    }

}
