/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ServiceQueryFormDTO;
import org.openapitools.client.model.ServiceQueryFormListDTO;
import org.openapitools.client.model.ServiceQueryResultDTO;
import org.openapitools.client.model.ServiceRegistryRequestDTO;
import org.openapitools.client.model.ServiceRegistryResponseDTO;
import org.openapitools.client.model.SystemRequestDTO;
import org.openapitools.client.model.SystemResponseDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ClientApi
 */
@Disabled
public class ClientApiTest {

    private final ClientApi api = new ClientApi();

    /**
     * Return an echo message with the purpose of testing the core service availability
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void echoServiceUsingGETTest() throws ApiException {
        String response = api.echoServiceUsingGET();
        // TODO: test validations
    }

    /**
     * Return Service Registry data that fits the specification
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void multiQueryRegistryUsingPOSTTest() throws ApiException {
        ServiceQueryFormListDTO forms = null;
        ServiceQueryResultDTO response = api.multiQueryRegistryUsingPOST(forms);
        // TODO: test validations
    }

    /**
     * Return Service Registry data that fits the specification
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryRegistryUsingPOSTTest() throws ApiException {
        ServiceQueryFormDTO form = null;
        ServiceQueryResultDTO response = api.queryRegistryUsingPOST(form);
        // TODO: test validations
    }

    /**
     * Registers a service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerServiceUsingPOSTTest() throws ApiException {
        ServiceRegistryRequestDTO dto = null;
        ServiceRegistryResponseDTO response = api.registerServiceUsingPOST(dto);
        // TODO: test validations
    }

    /**
     * Return created application system 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerSystemUsingPOSTTest() throws ApiException {
        SystemRequestDTO dto = null;
        SystemResponseDTO response = api.registerSystemUsingPOST(dto);
        // TODO: test validations
    }

    /**
     * Remove a registered service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unregisterServiceUsingDELETETest() throws ApiException {
        Integer port = null;
        String serviceDefinition = null;
        String serviceUri = null;
        String systemName = null;
        String address = null;
        api.unregisterServiceUsingDELETE(port, serviceDefinition, serviceUri, systemName, address);
        // TODO: test validations
    }

    /**
     * Unregister the given system
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unregisterSystemUsingDELETETest() throws ApiException {
        Integer port = null;
        String systemName = null;
        String address = null;
        api.unregisterSystemUsingDELETE(port, systemName, address);
        // TODO: test validations
    }

}
