/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.LogEntryListResponseDTO;
import org.openapitools.client.model.ServiceDefinitionRequestDTO;
import org.openapitools.client.model.ServiceDefinitionResponseDTO;
import org.openapitools.client.model.ServiceDefinitionsListResponseDTO;
import org.openapitools.client.model.ServiceInterfaceRequestDTO;
import org.openapitools.client.model.ServiceInterfaceResponseDTO;
import org.openapitools.client.model.ServiceInterfacesListResponseDTO;
import org.openapitools.client.model.ServiceRegistryGroupedResponseDTO;
import org.openapitools.client.model.ServiceRegistryListResponseDTO;
import org.openapitools.client.model.ServiceRegistryRequestDTO;
import org.openapitools.client.model.ServiceRegistryResponseDTO;
import org.openapitools.client.model.SystemListResponseDTO;
import org.openapitools.client.model.SystemRequestDTO;
import org.openapitools.client.model.SystemResponseDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManagementApi
 */
@Disabled
public class ManagementApiTest {

    private final ManagementApi api = new ManagementApi();

    /**
     * Return created service definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addServiceDefinitionUsingPOSTTest() throws ApiException {
        ServiceDefinitionRequestDTO serviceDefinitionRequestDTO = null;
        ServiceDefinitionResponseDTO response = api.addServiceDefinitionUsingPOST(serviceDefinitionRequestDTO);
        // TODO: test validations
    }

    /**
     * Return created service interface
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addServiceInterfaceUsingPOSTTest() throws ApiException {
        ServiceInterfaceRequestDTO serviceInterfaceRequestDTO = null;
        ServiceInterfaceResponseDTO response = api.addServiceInterfaceUsingPOST(serviceInterfaceRequestDTO);
        // TODO: test validations
    }

    /**
     * Registers a service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addServiceRegistryUsingPOSTTest() throws ApiException {
        ServiceRegistryRequestDTO request = null;
        ServiceRegistryResponseDTO response = api.addServiceRegistryUsingPOST(request);
        // TODO: test validations
    }

    /**
     * Return created system 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void addSystemUsingPOSTTest() throws ApiException {
        SystemRequestDTO request = null;
        SystemResponseDTO response = api.addSystemUsingPOST(request);
        // TODO: test validations
    }

    /**
     * Return requested log entries by the given parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getLogEntriesUsingGETTest() throws ApiException {
        String direction = null;
        String from = null;
        Integer itemPerPage = null;
        String level = null;
        String logger = null;
        Integer page = null;
        String sortField = null;
        String to = null;
        LogEntryListResponseDTO response = api.getLogEntriesUsingGET(direction, from, itemPerPage, level, logger, page, sortField, to);
        // TODO: test validations
    }

    /**
     * Return requested service definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceDefinitionByIdUsingGETTest() throws ApiException {
        Long id = null;
        ServiceDefinitionResponseDTO response = api.getServiceDefinitionByIdUsingGET(id);
        // TODO: test validations
    }

    /**
     * Return requested service definitions by the given parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceDefinitionsUsingGETTest() throws ApiException {
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        ServiceDefinitionsListResponseDTO response = api.getServiceDefinitionsUsingGET(direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Return requested service interface
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceInterfaceByIdUsingGETTest() throws ApiException {
        Long id = null;
        ServiceInterfaceResponseDTO response = api.getServiceInterfaceByIdUsingGET(id);
        // TODO: test validations
    }

    /**
     * Return requested service interfaces by the given parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceInterfacesUsingGETTest() throws ApiException {
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        ServiceInterfacesListResponseDTO response = api.getServiceInterfacesUsingGET(direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Return requested service registry entries by service definition based on the given parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryEntriesByServiceDefinitionUsingGETTest() throws ApiException {
        String serviceDefinition = null;
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        ServiceRegistryListResponseDTO response = api.getServiceRegistryEntriesByServiceDefinitionUsingGET(serviceDefinition, direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Return requested service registry entries by the given parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryEntriesUsingGETTest() throws ApiException {
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        ServiceRegistryListResponseDTO response = api.getServiceRegistryEntriesUsingGET(direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Return requested service registry entry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryEntryByIdUsingGETTest() throws ApiException {
        Long id = null;
        ServiceRegistryResponseDTO response = api.getServiceRegistryEntryByIdUsingGET(id);
        // TODO: test validations
    }

    /**
     * Return all service registry entries grouped for frontend usage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryGroupedDataUsingGETTest() throws ApiException {
        ServiceRegistryGroupedResponseDTO response = api.getServiceRegistryGroupedDataUsingGET();
        // TODO: test validations
    }

    /**
     * Return system by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSystemByIdUsingGETTest() throws ApiException {
        Long id = null;
        SystemResponseDTO response = api.getSystemByIdUsingGET(id);
        // TODO: test validations
    }

    /**
     * Return systems by request parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSystemsUsingGETTest() throws ApiException {
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        SystemListResponseDTO response = api.getSystemsUsingGET(direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Merge/Patch a service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void mergeServiceRegistryUsingPATCHTest() throws ApiException {
        Long id = null;
        ServiceRegistryRequestDTO request = null;
        ServiceRegistryResponseDTO response = api.mergeServiceRegistryUsingPATCH(id, request);
        // TODO: test validations
    }

    /**
     * Return system  updated by fields
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void mergeSystemUsingPATCHTest() throws ApiException {
        Long id = null;
        SystemRequestDTO request = null;
        SystemResponseDTO response = api.mergeSystemUsingPATCH(id, request);
        // TODO: test validations
    }

    /**
     * Return updated service definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchUpdateServiceDefinitionUsingPATCHTest() throws ApiException {
        Long id = null;
        ServiceDefinitionRequestDTO serviceDefinitionRequestDTO = null;
        ServiceDefinitionResponseDTO response = api.patchUpdateServiceDefinitionUsingPATCH(id, serviceDefinitionRequestDTO);
        // TODO: test validations
    }

    /**
     * Return updated service interface
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchUpdateServiceInterfaceUsingPATCHTest() throws ApiException {
        Long id = null;
        ServiceInterfaceRequestDTO serviceInterfaceRequestDTO = null;
        ServiceInterfaceResponseDTO response = api.patchUpdateServiceInterfaceUsingPATCH(id, serviceInterfaceRequestDTO);
        // TODO: test validations
    }

    /**
     * Return updated service definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putUpdateServiceDefinitionUsingPUTTest() throws ApiException {
        Long id = null;
        ServiceDefinitionRequestDTO serviceDefinitionRequestDTO = null;
        ServiceDefinitionResponseDTO response = api.putUpdateServiceDefinitionUsingPUT(id, serviceDefinitionRequestDTO);
        // TODO: test validations
    }

    /**
     * Return updated service interface
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void putUpdateServiceInterfaceUsingPUTTest() throws ApiException {
        Long id = null;
        ServiceInterfaceRequestDTO serviceInterfaceRequestDTO = null;
        ServiceInterfaceResponseDTO response = api.putUpdateServiceInterfaceUsingPUT(id, serviceInterfaceRequestDTO);
        // TODO: test validations
    }

    /**
     * Remove service definition
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeServiceDefinitionUsingDELETETest() throws ApiException {
        Long id = null;
        api.removeServiceDefinitionUsingDELETE(id);
        // TODO: test validations
    }

    /**
     * Remove service interface
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeServiceInterfaceUsingDELETETest() throws ApiException {
        Long id = null;
        api.removeServiceInterfaceUsingDELETE(id);
        // TODO: test validations
    }

    /**
     * Remove the specified service registry entry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeServiceRegistryEntryByIdUsingDELETETest() throws ApiException {
        Long id = null;
        api.removeServiceRegistryEntryByIdUsingDELETE(id);
        // TODO: test validations
    }

    /**
     * Remove system
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeSystemUsingDELETETest() throws ApiException {
        Long id = null;
        api.removeSystemUsingDELETE(id);
        // TODO: test validations
    }

    /**
     * Update a service
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateServiceRegistryUsingPUTTest() throws ApiException {
        Long id = null;
        ServiceRegistryRequestDTO request = null;
        ServiceRegistryResponseDTO response = api.updateServiceRegistryUsingPUT(id, request);
        // TODO: test validations
    }

    /**
     * Return updated system 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateSystemUsingPUTTest() throws ApiException {
        Long id = null;
        SystemRequestDTO request = null;
        SystemResponseDTO response = api.updateSystemUsingPUT(id, request);
        // TODO: test validations
    }

}
