/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.KeyValuesDTO;
import org.openapitools.client.model.ServiceRegistryListResponseDTO;
import org.openapitools.client.model.SystemListResponseDTO;
import org.openapitools.client.model.SystemRequestDTO;
import org.openapitools.client.model.SystemResponseDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PrivateApi
 */
@Disabled
public class PrivateApiTest {

    private final PrivateApi api = new PrivateApi();

    /**
     * Return service registry entries by system id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryEntriesBySystemIdUsingGETTest() throws ApiException {
        Long id = null;
        ServiceRegistryListResponseDTO response = api.getServiceRegistryEntriesBySystemIdUsingGET(id);
        // TODO: test validations
    }

    /**
     * Return all service registry entries
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getServiceRegistryEntriesUsingGET1Test() throws ApiException {
        ServiceRegistryListResponseDTO response = api.getServiceRegistryEntriesUsingGET1();
        // TODO: test validations
    }

    /**
     * Return some configuration of ServiceRegistry
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pullConfigUsingGETTest() throws ApiException {
        KeyValuesDTO response = api.pullConfigUsingGET();
        // TODO: test validations
    }

    /**
     * Return systems by request parameters
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pullSystemsUsingGETTest() throws ApiException {
        String direction = null;
        Integer itemPerPage = null;
        Integer page = null;
        String sortField = null;
        SystemListResponseDTO response = api.pullSystemsUsingGET(direction, itemPerPage, page, sortField);
        // TODO: test validations
    }

    /**
     * Return System by requested dto
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryRegistryBySystemDTOUsingPOSTTest() throws ApiException {
        SystemRequestDTO request = null;
        SystemResponseDTO response = api.queryRegistryBySystemDTOUsingPOST(request);
        // TODO: test validations
    }

    /**
     * Return system by requested id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryRegistryBySystemIdUsingGETTest() throws ApiException {
        Long id = null;
        SystemResponseDTO response = api.queryRegistryBySystemIdUsingGET(id);
        // TODO: test validations
    }

    /**
     * Return service registry entries by service definition list
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void queryServiceRegistryEntriesByServiceDefinitionListUsingPOSTTest() throws ApiException {
        List<String> request = null;
        ServiceRegistryListResponseDTO response = api.queryServiceRegistryEntriesByServiceDefinitionListUsingPOST(request);
        // TODO: test validations
    }

}
