/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.IdValueDTO;
import org.openapitools.client.model.SystemResponseDTO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * AutoCompleteDataResponseDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class AutoCompleteDataResponseDTO {
  public static final String SERIALIZED_NAME_INTERFACE_LIST = "interfaceList";
  @SerializedName(SERIALIZED_NAME_INTERFACE_LIST)
  private List<IdValueDTO> interfaceList = new ArrayList<>();

  public static final String SERIALIZED_NAME_SERVICE_LIST = "serviceList";
  @SerializedName(SERIALIZED_NAME_SERVICE_LIST)
  private List<IdValueDTO> serviceList = new ArrayList<>();

  public static final String SERIALIZED_NAME_SYSTEM_LIST = "systemList";
  @SerializedName(SERIALIZED_NAME_SYSTEM_LIST)
  private List<SystemResponseDTO> systemList = new ArrayList<>();

  public AutoCompleteDataResponseDTO() {
  }

  public AutoCompleteDataResponseDTO interfaceList(List<IdValueDTO> interfaceList) {
    this.interfaceList = interfaceList;
    return this;
  }

  public AutoCompleteDataResponseDTO addInterfaceListItem(IdValueDTO interfaceListItem) {
    if (this.interfaceList == null) {
      this.interfaceList = new ArrayList<>();
    }
    this.interfaceList.add(interfaceListItem);
    return this;
  }

  /**
   * Get interfaceList
   * @return interfaceList
   */
  @javax.annotation.Nullable
  public List<IdValueDTO> getInterfaceList() {
    return interfaceList;
  }

  public void setInterfaceList(List<IdValueDTO> interfaceList) {
    this.interfaceList = interfaceList;
  }


  public AutoCompleteDataResponseDTO serviceList(List<IdValueDTO> serviceList) {
    this.serviceList = serviceList;
    return this;
  }

  public AutoCompleteDataResponseDTO addServiceListItem(IdValueDTO serviceListItem) {
    if (this.serviceList == null) {
      this.serviceList = new ArrayList<>();
    }
    this.serviceList.add(serviceListItem);
    return this;
  }

  /**
   * Get serviceList
   * @return serviceList
   */
  @javax.annotation.Nullable
  public List<IdValueDTO> getServiceList() {
    return serviceList;
  }

  public void setServiceList(List<IdValueDTO> serviceList) {
    this.serviceList = serviceList;
  }


  public AutoCompleteDataResponseDTO systemList(List<SystemResponseDTO> systemList) {
    this.systemList = systemList;
    return this;
  }

  public AutoCompleteDataResponseDTO addSystemListItem(SystemResponseDTO systemListItem) {
    if (this.systemList == null) {
      this.systemList = new ArrayList<>();
    }
    this.systemList.add(systemListItem);
    return this;
  }

  /**
   * Get systemList
   * @return systemList
   */
  @javax.annotation.Nullable
  public List<SystemResponseDTO> getSystemList() {
    return systemList;
  }

  public void setSystemList(List<SystemResponseDTO> systemList) {
    this.systemList = systemList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoCompleteDataResponseDTO autoCompleteDataResponseDTO = (AutoCompleteDataResponseDTO) o;
    return Objects.equals(this.interfaceList, autoCompleteDataResponseDTO.interfaceList) &&
        Objects.equals(this.serviceList, autoCompleteDataResponseDTO.serviceList) &&
        Objects.equals(this.systemList, autoCompleteDataResponseDTO.systemList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interfaceList, serviceList, systemList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoCompleteDataResponseDTO {\n");
    sb.append("    interfaceList: ").append(toIndentedString(interfaceList)).append("\n");
    sb.append("    serviceList: ").append(toIndentedString(serviceList)).append("\n");
    sb.append("    systemList: ").append(toIndentedString(systemList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("interfaceList");
    openapiFields.add("serviceList");
    openapiFields.add("systemList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AutoCompleteDataResponseDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AutoCompleteDataResponseDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AutoCompleteDataResponseDTO is not found in the empty JSON string", AutoCompleteDataResponseDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AutoCompleteDataResponseDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AutoCompleteDataResponseDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("interfaceList") != null && !jsonObj.get("interfaceList").isJsonNull()) {
        JsonArray jsonArrayinterfaceList = jsonObj.getAsJsonArray("interfaceList");
        if (jsonArrayinterfaceList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("interfaceList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `interfaceList` to be an array in the JSON string but got `%s`", jsonObj.get("interfaceList").toString()));
          }

          // validate the optional field `interfaceList` (array)
          for (int i = 0; i < jsonArrayinterfaceList.size(); i++) {
            IdValueDTO.validateJsonElement(jsonArrayinterfaceList.get(i));
          };
        }
      }
      if (jsonObj.get("serviceList") != null && !jsonObj.get("serviceList").isJsonNull()) {
        JsonArray jsonArrayserviceList = jsonObj.getAsJsonArray("serviceList");
        if (jsonArrayserviceList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("serviceList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `serviceList` to be an array in the JSON string but got `%s`", jsonObj.get("serviceList").toString()));
          }

          // validate the optional field `serviceList` (array)
          for (int i = 0; i < jsonArrayserviceList.size(); i++) {
            IdValueDTO.validateJsonElement(jsonArrayserviceList.get(i));
          };
        }
      }
      if (jsonObj.get("systemList") != null && !jsonObj.get("systemList").isJsonNull()) {
        JsonArray jsonArraysystemList = jsonObj.getAsJsonArray("systemList");
        if (jsonArraysystemList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("systemList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `systemList` to be an array in the JSON string but got `%s`", jsonObj.get("systemList").toString()));
          }

          // validate the optional field `systemList` (array)
          for (int i = 0; i < jsonArraysystemList.size(); i++) {
            SystemResponseDTO.validateJsonElement(jsonArraysystemList.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AutoCompleteDataResponseDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AutoCompleteDataResponseDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AutoCompleteDataResponseDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AutoCompleteDataResponseDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<AutoCompleteDataResponseDTO>() {
           @Override
           public void write(JsonWriter out, AutoCompleteDataResponseDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AutoCompleteDataResponseDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AutoCompleteDataResponseDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AutoCompleteDataResponseDTO
   * @throws IOException if the JSON string is invalid with respect to AutoCompleteDataResponseDTO
   */
  public static AutoCompleteDataResponseDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AutoCompleteDataResponseDTO.class);
  }

  /**
   * Convert an instance of AutoCompleteDataResponseDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

