/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServiceQueryFormDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class ServiceQueryFormDTO {
  public static final String SERIALIZED_NAME_INTERFACE_REQUIREMENTS = "interfaceRequirements";
  @SerializedName(SERIALIZED_NAME_INTERFACE_REQUIREMENTS)
  private List<String> interfaceRequirements = new ArrayList<>();

  public static final String SERIALIZED_NAME_MAX_VERSION_REQUIREMENT = "maxVersionRequirement";
  @SerializedName(SERIALIZED_NAME_MAX_VERSION_REQUIREMENT)
  private Integer maxVersionRequirement;

  public static final String SERIALIZED_NAME_METADATA_REQUIREMENTS = "metadataRequirements";
  @SerializedName(SERIALIZED_NAME_METADATA_REQUIREMENTS)
  private Map<String, String> metadataRequirements = new HashMap<>();

  public static final String SERIALIZED_NAME_MIN_VERSION_REQUIREMENT = "minVersionRequirement";
  @SerializedName(SERIALIZED_NAME_MIN_VERSION_REQUIREMENT)
  private Integer minVersionRequirement;

  public static final String SERIALIZED_NAME_PING_PROVIDERS = "pingProviders";
  @SerializedName(SERIALIZED_NAME_PING_PROVIDERS)
  private Boolean pingProviders;

  /**
   * Gets or Sets providerAddressTypeRequirements
   */
  @JsonAdapter(ProviderAddressTypeRequirementsEnum.Adapter.class)
  public enum ProviderAddressTypeRequirementsEnum {
    HOSTNAME("HOSTNAME"),
    
    IPV4("IPV4"),
    
    IPV6("IPV6");

    private String value;

    ProviderAddressTypeRequirementsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ProviderAddressTypeRequirementsEnum fromValue(String value) {
      for (ProviderAddressTypeRequirementsEnum b : ProviderAddressTypeRequirementsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ProviderAddressTypeRequirementsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ProviderAddressTypeRequirementsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ProviderAddressTypeRequirementsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ProviderAddressTypeRequirementsEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ProviderAddressTypeRequirementsEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PROVIDER_ADDRESS_TYPE_REQUIREMENTS = "providerAddressTypeRequirements";
  @SerializedName(SERIALIZED_NAME_PROVIDER_ADDRESS_TYPE_REQUIREMENTS)
  private List<ProviderAddressTypeRequirementsEnum> providerAddressTypeRequirements = new ArrayList<>();

  /**
   * Gets or Sets securityRequirements
   */
  @JsonAdapter(SecurityRequirementsEnum.Adapter.class)
  public enum SecurityRequirementsEnum {
    NOT_SECURE("NOT_SECURE"),
    
    CERTIFICATE("CERTIFICATE"),
    
    TOKEN("TOKEN");

    private String value;

    SecurityRequirementsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SecurityRequirementsEnum fromValue(String value) {
      for (SecurityRequirementsEnum b : SecurityRequirementsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SecurityRequirementsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SecurityRequirementsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SecurityRequirementsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SecurityRequirementsEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      SecurityRequirementsEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SECURITY_REQUIREMENTS = "securityRequirements";
  @SerializedName(SERIALIZED_NAME_SECURITY_REQUIREMENTS)
  private List<SecurityRequirementsEnum> securityRequirements = new ArrayList<>();

  public static final String SERIALIZED_NAME_SERVICE_DEFINITION_REQUIREMENT = "serviceDefinitionRequirement";
  @SerializedName(SERIALIZED_NAME_SERVICE_DEFINITION_REQUIREMENT)
  private String serviceDefinitionRequirement;

  public static final String SERIALIZED_NAME_VERSION_REQUIREMENT = "versionRequirement";
  @SerializedName(SERIALIZED_NAME_VERSION_REQUIREMENT)
  private Integer versionRequirement;

  public ServiceQueryFormDTO() {
  }

  public ServiceQueryFormDTO interfaceRequirements(List<String> interfaceRequirements) {
    this.interfaceRequirements = interfaceRequirements;
    return this;
  }

  public ServiceQueryFormDTO addInterfaceRequirementsItem(String interfaceRequirementsItem) {
    if (this.interfaceRequirements == null) {
      this.interfaceRequirements = new ArrayList<>();
    }
    this.interfaceRequirements.add(interfaceRequirementsItem);
    return this;
  }

  /**
   * Get interfaceRequirements
   * @return interfaceRequirements
   */
  @javax.annotation.Nullable
  public List<String> getInterfaceRequirements() {
    return interfaceRequirements;
  }

  public void setInterfaceRequirements(List<String> interfaceRequirements) {
    this.interfaceRequirements = interfaceRequirements;
  }


  public ServiceQueryFormDTO maxVersionRequirement(Integer maxVersionRequirement) {
    this.maxVersionRequirement = maxVersionRequirement;
    return this;
  }

  /**
   * Get maxVersionRequirement
   * @return maxVersionRequirement
   */
  @javax.annotation.Nullable
  public Integer getMaxVersionRequirement() {
    return maxVersionRequirement;
  }

  public void setMaxVersionRequirement(Integer maxVersionRequirement) {
    this.maxVersionRequirement = maxVersionRequirement;
  }


  public ServiceQueryFormDTO metadataRequirements(Map<String, String> metadataRequirements) {
    this.metadataRequirements = metadataRequirements;
    return this;
  }

  public ServiceQueryFormDTO putMetadataRequirementsItem(String key, String metadataRequirementsItem) {
    if (this.metadataRequirements == null) {
      this.metadataRequirements = new HashMap<>();
    }
    this.metadataRequirements.put(key, metadataRequirementsItem);
    return this;
  }

  /**
   * Get metadataRequirements
   * @return metadataRequirements
   */
  @javax.annotation.Nullable
  public Map<String, String> getMetadataRequirements() {
    return metadataRequirements;
  }

  public void setMetadataRequirements(Map<String, String> metadataRequirements) {
    this.metadataRequirements = metadataRequirements;
  }


  public ServiceQueryFormDTO minVersionRequirement(Integer minVersionRequirement) {
    this.minVersionRequirement = minVersionRequirement;
    return this;
  }

  /**
   * Get minVersionRequirement
   * @return minVersionRequirement
   */
  @javax.annotation.Nullable
  public Integer getMinVersionRequirement() {
    return minVersionRequirement;
  }

  public void setMinVersionRequirement(Integer minVersionRequirement) {
    this.minVersionRequirement = minVersionRequirement;
  }


  public ServiceQueryFormDTO pingProviders(Boolean pingProviders) {
    this.pingProviders = pingProviders;
    return this;
  }

  /**
   * Get pingProviders
   * @return pingProviders
   */
  @javax.annotation.Nullable
  public Boolean getPingProviders() {
    return pingProviders;
  }

  public void setPingProviders(Boolean pingProviders) {
    this.pingProviders = pingProviders;
  }


  public ServiceQueryFormDTO providerAddressTypeRequirements(List<ProviderAddressTypeRequirementsEnum> providerAddressTypeRequirements) {
    this.providerAddressTypeRequirements = providerAddressTypeRequirements;
    return this;
  }

  public ServiceQueryFormDTO addProviderAddressTypeRequirementsItem(ProviderAddressTypeRequirementsEnum providerAddressTypeRequirementsItem) {
    if (this.providerAddressTypeRequirements == null) {
      this.providerAddressTypeRequirements = new ArrayList<>();
    }
    this.providerAddressTypeRequirements.add(providerAddressTypeRequirementsItem);
    return this;
  }

  /**
   * Get providerAddressTypeRequirements
   * @return providerAddressTypeRequirements
   */
  @javax.annotation.Nullable
  public List<ProviderAddressTypeRequirementsEnum> getProviderAddressTypeRequirements() {
    return providerAddressTypeRequirements;
  }

  public void setProviderAddressTypeRequirements(List<ProviderAddressTypeRequirementsEnum> providerAddressTypeRequirements) {
    this.providerAddressTypeRequirements = providerAddressTypeRequirements;
  }


  public ServiceQueryFormDTO securityRequirements(List<SecurityRequirementsEnum> securityRequirements) {
    this.securityRequirements = securityRequirements;
    return this;
  }

  public ServiceQueryFormDTO addSecurityRequirementsItem(SecurityRequirementsEnum securityRequirementsItem) {
    if (this.securityRequirements == null) {
      this.securityRequirements = new ArrayList<>();
    }
    this.securityRequirements.add(securityRequirementsItem);
    return this;
  }

  /**
   * Get securityRequirements
   * @return securityRequirements
   */
  @javax.annotation.Nullable
  public List<SecurityRequirementsEnum> getSecurityRequirements() {
    return securityRequirements;
  }

  public void setSecurityRequirements(List<SecurityRequirementsEnum> securityRequirements) {
    this.securityRequirements = securityRequirements;
  }


  public ServiceQueryFormDTO serviceDefinitionRequirement(String serviceDefinitionRequirement) {
    this.serviceDefinitionRequirement = serviceDefinitionRequirement;
    return this;
  }

  /**
   * Get serviceDefinitionRequirement
   * @return serviceDefinitionRequirement
   */
  @javax.annotation.Nullable
  public String getServiceDefinitionRequirement() {
    return serviceDefinitionRequirement;
  }

  public void setServiceDefinitionRequirement(String serviceDefinitionRequirement) {
    this.serviceDefinitionRequirement = serviceDefinitionRequirement;
  }


  public ServiceQueryFormDTO versionRequirement(Integer versionRequirement) {
    this.versionRequirement = versionRequirement;
    return this;
  }

  /**
   * Get versionRequirement
   * @return versionRequirement
   */
  @javax.annotation.Nullable
  public Integer getVersionRequirement() {
    return versionRequirement;
  }

  public void setVersionRequirement(Integer versionRequirement) {
    this.versionRequirement = versionRequirement;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceQueryFormDTO serviceQueryFormDTO = (ServiceQueryFormDTO) o;
    return Objects.equals(this.interfaceRequirements, serviceQueryFormDTO.interfaceRequirements) &&
        Objects.equals(this.maxVersionRequirement, serviceQueryFormDTO.maxVersionRequirement) &&
        Objects.equals(this.metadataRequirements, serviceQueryFormDTO.metadataRequirements) &&
        Objects.equals(this.minVersionRequirement, serviceQueryFormDTO.minVersionRequirement) &&
        Objects.equals(this.pingProviders, serviceQueryFormDTO.pingProviders) &&
        Objects.equals(this.providerAddressTypeRequirements, serviceQueryFormDTO.providerAddressTypeRequirements) &&
        Objects.equals(this.securityRequirements, serviceQueryFormDTO.securityRequirements) &&
        Objects.equals(this.serviceDefinitionRequirement, serviceQueryFormDTO.serviceDefinitionRequirement) &&
        Objects.equals(this.versionRequirement, serviceQueryFormDTO.versionRequirement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interfaceRequirements, maxVersionRequirement, metadataRequirements, minVersionRequirement, pingProviders, providerAddressTypeRequirements, securityRequirements, serviceDefinitionRequirement, versionRequirement);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceQueryFormDTO {\n");
    sb.append("    interfaceRequirements: ").append(toIndentedString(interfaceRequirements)).append("\n");
    sb.append("    maxVersionRequirement: ").append(toIndentedString(maxVersionRequirement)).append("\n");
    sb.append("    metadataRequirements: ").append(toIndentedString(metadataRequirements)).append("\n");
    sb.append("    minVersionRequirement: ").append(toIndentedString(minVersionRequirement)).append("\n");
    sb.append("    pingProviders: ").append(toIndentedString(pingProviders)).append("\n");
    sb.append("    providerAddressTypeRequirements: ").append(toIndentedString(providerAddressTypeRequirements)).append("\n");
    sb.append("    securityRequirements: ").append(toIndentedString(securityRequirements)).append("\n");
    sb.append("    serviceDefinitionRequirement: ").append(toIndentedString(serviceDefinitionRequirement)).append("\n");
    sb.append("    versionRequirement: ").append(toIndentedString(versionRequirement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("interfaceRequirements");
    openapiFields.add("maxVersionRequirement");
    openapiFields.add("metadataRequirements");
    openapiFields.add("minVersionRequirement");
    openapiFields.add("pingProviders");
    openapiFields.add("providerAddressTypeRequirements");
    openapiFields.add("securityRequirements");
    openapiFields.add("serviceDefinitionRequirement");
    openapiFields.add("versionRequirement");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceQueryFormDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceQueryFormDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceQueryFormDTO is not found in the empty JSON string", ServiceQueryFormDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceQueryFormDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceQueryFormDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("interfaceRequirements") != null && !jsonObj.get("interfaceRequirements").isJsonNull() && !jsonObj.get("interfaceRequirements").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `interfaceRequirements` to be an array in the JSON string but got `%s`", jsonObj.get("interfaceRequirements").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("providerAddressTypeRequirements") != null && !jsonObj.get("providerAddressTypeRequirements").isJsonNull() && !jsonObj.get("providerAddressTypeRequirements").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `providerAddressTypeRequirements` to be an array in the JSON string but got `%s`", jsonObj.get("providerAddressTypeRequirements").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("securityRequirements") != null && !jsonObj.get("securityRequirements").isJsonNull() && !jsonObj.get("securityRequirements").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `securityRequirements` to be an array in the JSON string but got `%s`", jsonObj.get("securityRequirements").toString()));
      }
      if ((jsonObj.get("serviceDefinitionRequirement") != null && !jsonObj.get("serviceDefinitionRequirement").isJsonNull()) && !jsonObj.get("serviceDefinitionRequirement").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serviceDefinitionRequirement` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serviceDefinitionRequirement").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceQueryFormDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceQueryFormDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceQueryFormDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceQueryFormDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceQueryFormDTO>() {
           @Override
           public void write(JsonWriter out, ServiceQueryFormDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceQueryFormDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceQueryFormDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceQueryFormDTO
   * @throws IOException if the JSON string is invalid with respect to ServiceQueryFormDTO
   */
  public static ServiceQueryFormDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceQueryFormDTO.class);
  }

  /**
   * Convert an instance of ServiceQueryFormDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

