/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AutoCompleteDataResponseDTO;
import org.openapitools.client.model.ServicesGroupedByServiceDefinitionResponseDTO;
import org.openapitools.client.model.ServicesGroupedBySystemsResponseDTO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServiceRegistryGroupedResponseDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class ServiceRegistryGroupedResponseDTO {
  public static final String SERIALIZED_NAME_AUTO_COMPLETE_DATA = "autoCompleteData";
  @SerializedName(SERIALIZED_NAME_AUTO_COMPLETE_DATA)
  private AutoCompleteDataResponseDTO autoCompleteData;

  public static final String SERIALIZED_NAME_SERVICES_GROUPED_BY_SERVICE_DEFINITION = "servicesGroupedByServiceDefinition";
  @SerializedName(SERIALIZED_NAME_SERVICES_GROUPED_BY_SERVICE_DEFINITION)
  private List<ServicesGroupedByServiceDefinitionResponseDTO> servicesGroupedByServiceDefinition = new ArrayList<>();

  public static final String SERIALIZED_NAME_SERVICES_GROUPED_BY_SYSTEMS = "servicesGroupedBySystems";
  @SerializedName(SERIALIZED_NAME_SERVICES_GROUPED_BY_SYSTEMS)
  private List<ServicesGroupedBySystemsResponseDTO> servicesGroupedBySystems = new ArrayList<>();

  public ServiceRegistryGroupedResponseDTO() {
  }

  public ServiceRegistryGroupedResponseDTO autoCompleteData(AutoCompleteDataResponseDTO autoCompleteData) {
    this.autoCompleteData = autoCompleteData;
    return this;
  }

  /**
   * Get autoCompleteData
   * @return autoCompleteData
   */
  @javax.annotation.Nullable
  public AutoCompleteDataResponseDTO getAutoCompleteData() {
    return autoCompleteData;
  }

  public void setAutoCompleteData(AutoCompleteDataResponseDTO autoCompleteData) {
    this.autoCompleteData = autoCompleteData;
  }


  public ServiceRegistryGroupedResponseDTO servicesGroupedByServiceDefinition(List<ServicesGroupedByServiceDefinitionResponseDTO> servicesGroupedByServiceDefinition) {
    this.servicesGroupedByServiceDefinition = servicesGroupedByServiceDefinition;
    return this;
  }

  public ServiceRegistryGroupedResponseDTO addServicesGroupedByServiceDefinitionItem(ServicesGroupedByServiceDefinitionResponseDTO servicesGroupedByServiceDefinitionItem) {
    if (this.servicesGroupedByServiceDefinition == null) {
      this.servicesGroupedByServiceDefinition = new ArrayList<>();
    }
    this.servicesGroupedByServiceDefinition.add(servicesGroupedByServiceDefinitionItem);
    return this;
  }

  /**
   * Get servicesGroupedByServiceDefinition
   * @return servicesGroupedByServiceDefinition
   */
  @javax.annotation.Nullable
  public List<ServicesGroupedByServiceDefinitionResponseDTO> getServicesGroupedByServiceDefinition() {
    return servicesGroupedByServiceDefinition;
  }

  public void setServicesGroupedByServiceDefinition(List<ServicesGroupedByServiceDefinitionResponseDTO> servicesGroupedByServiceDefinition) {
    this.servicesGroupedByServiceDefinition = servicesGroupedByServiceDefinition;
  }


  public ServiceRegistryGroupedResponseDTO servicesGroupedBySystems(List<ServicesGroupedBySystemsResponseDTO> servicesGroupedBySystems) {
    this.servicesGroupedBySystems = servicesGroupedBySystems;
    return this;
  }

  public ServiceRegistryGroupedResponseDTO addServicesGroupedBySystemsItem(ServicesGroupedBySystemsResponseDTO servicesGroupedBySystemsItem) {
    if (this.servicesGroupedBySystems == null) {
      this.servicesGroupedBySystems = new ArrayList<>();
    }
    this.servicesGroupedBySystems.add(servicesGroupedBySystemsItem);
    return this;
  }

  /**
   * Get servicesGroupedBySystems
   * @return servicesGroupedBySystems
   */
  @javax.annotation.Nullable
  public List<ServicesGroupedBySystemsResponseDTO> getServicesGroupedBySystems() {
    return servicesGroupedBySystems;
  }

  public void setServicesGroupedBySystems(List<ServicesGroupedBySystemsResponseDTO> servicesGroupedBySystems) {
    this.servicesGroupedBySystems = servicesGroupedBySystems;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceRegistryGroupedResponseDTO serviceRegistryGroupedResponseDTO = (ServiceRegistryGroupedResponseDTO) o;
    return Objects.equals(this.autoCompleteData, serviceRegistryGroupedResponseDTO.autoCompleteData) &&
        Objects.equals(this.servicesGroupedByServiceDefinition, serviceRegistryGroupedResponseDTO.servicesGroupedByServiceDefinition) &&
        Objects.equals(this.servicesGroupedBySystems, serviceRegistryGroupedResponseDTO.servicesGroupedBySystems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoCompleteData, servicesGroupedByServiceDefinition, servicesGroupedBySystems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceRegistryGroupedResponseDTO {\n");
    sb.append("    autoCompleteData: ").append(toIndentedString(autoCompleteData)).append("\n");
    sb.append("    servicesGroupedByServiceDefinition: ").append(toIndentedString(servicesGroupedByServiceDefinition)).append("\n");
    sb.append("    servicesGroupedBySystems: ").append(toIndentedString(servicesGroupedBySystems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("autoCompleteData");
    openapiFields.add("servicesGroupedByServiceDefinition");
    openapiFields.add("servicesGroupedBySystems");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceRegistryGroupedResponseDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceRegistryGroupedResponseDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceRegistryGroupedResponseDTO is not found in the empty JSON string", ServiceRegistryGroupedResponseDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceRegistryGroupedResponseDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceRegistryGroupedResponseDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `autoCompleteData`
      if (jsonObj.get("autoCompleteData") != null && !jsonObj.get("autoCompleteData").isJsonNull()) {
        AutoCompleteDataResponseDTO.validateJsonElement(jsonObj.get("autoCompleteData"));
      }
      if (jsonObj.get("servicesGroupedByServiceDefinition") != null && !jsonObj.get("servicesGroupedByServiceDefinition").isJsonNull()) {
        JsonArray jsonArrayservicesGroupedByServiceDefinition = jsonObj.getAsJsonArray("servicesGroupedByServiceDefinition");
        if (jsonArrayservicesGroupedByServiceDefinition != null) {
          // ensure the json data is an array
          if (!jsonObj.get("servicesGroupedByServiceDefinition").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `servicesGroupedByServiceDefinition` to be an array in the JSON string but got `%s`", jsonObj.get("servicesGroupedByServiceDefinition").toString()));
          }

          // validate the optional field `servicesGroupedByServiceDefinition` (array)
          for (int i = 0; i < jsonArrayservicesGroupedByServiceDefinition.size(); i++) {
            ServicesGroupedByServiceDefinitionResponseDTO.validateJsonElement(jsonArrayservicesGroupedByServiceDefinition.get(i));
          };
        }
      }
      if (jsonObj.get("servicesGroupedBySystems") != null && !jsonObj.get("servicesGroupedBySystems").isJsonNull()) {
        JsonArray jsonArrayservicesGroupedBySystems = jsonObj.getAsJsonArray("servicesGroupedBySystems");
        if (jsonArrayservicesGroupedBySystems != null) {
          // ensure the json data is an array
          if (!jsonObj.get("servicesGroupedBySystems").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `servicesGroupedBySystems` to be an array in the JSON string but got `%s`", jsonObj.get("servicesGroupedBySystems").toString()));
          }

          // validate the optional field `servicesGroupedBySystems` (array)
          for (int i = 0; i < jsonArrayservicesGroupedBySystems.size(); i++) {
            ServicesGroupedBySystemsResponseDTO.validateJsonElement(jsonArrayservicesGroupedBySystems.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceRegistryGroupedResponseDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceRegistryGroupedResponseDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceRegistryGroupedResponseDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceRegistryGroupedResponseDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceRegistryGroupedResponseDTO>() {
           @Override
           public void write(JsonWriter out, ServiceRegistryGroupedResponseDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceRegistryGroupedResponseDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceRegistryGroupedResponseDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceRegistryGroupedResponseDTO
   * @throws IOException if the JSON string is invalid with respect to ServiceRegistryGroupedResponseDTO
   */
  public static ServiceRegistryGroupedResponseDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceRegistryGroupedResponseDTO.class);
  }

  /**
   * Convert an instance of ServiceRegistryGroupedResponseDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

