/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for KeyValuesDTO
 */
public class KeyValuesDTOTest {
    private final KeyValuesDTO model = new KeyValuesDTO();

    /**
     * Model tests for KeyValuesDTO
     */
    @Test
    public void testKeyValuesDTO() {
        // TODO: test KeyValuesDTO
    }

    /**
     * Test the property 'map'
     */
    @Test
    public void mapTest() {
        // TODO: test map
    }

}
