/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LogEntryDTO
 */
public class LogEntryDTOTest {
    private final LogEntryDTO model = new LogEntryDTO();

    /**
     * Model tests for LogEntryDTO
     */
    @Test
    public void testLogEntryDTO() {
        // TODO: test LogEntryDTO
    }

    /**
     * Test the property 'entryDate'
     */
    @Test
    public void entryDateTest() {
        // TODO: test entryDate
    }

    /**
     * Test the property 'exception'
     */
    @Test
    public void exceptionTest() {
        // TODO: test exception
    }

    /**
     * Test the property 'logId'
     */
    @Test
    public void logIdTest() {
        // TODO: test logId
    }

    /**
     * Test the property 'logLevel'
     */
    @Test
    public void logLevelTest() {
        // TODO: test logLevel
    }

    /**
     * Test the property 'logger'
     */
    @Test
    public void loggerTest() {
        // TODO: test logger
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'systemName'
     */
    @Test
    public void systemNameTest() {
        // TODO: test systemName
    }

}
