/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ServiceRegistryResponseDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServicesGroupedBySystemsResponseDTO
 */
public class ServicesGroupedBySystemsResponseDTOTest {
    private final ServicesGroupedBySystemsResponseDTO model = new ServicesGroupedBySystemsResponseDTO();

    /**
     * Model tests for ServicesGroupedBySystemsResponseDTO
     */
    @Test
    public void testServicesGroupedBySystemsResponseDTO() {
        // TODO: test ServicesGroupedBySystemsResponseDTO
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'services'
     */
    @Test
    public void servicesTest() {
        // TODO: test services
    }

    /**
     * Test the property 'systemId'
     */
    @Test
    public void systemIdTest() {
        // TODO: test systemId
    }

    /**
     * Test the property 'systemName'
     */
    @Test
    public void systemNameTest() {
        // TODO: test systemName
    }

}
