/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceQueryFormDTO
 */
public class ServiceQueryFormDTOTest {
    private final ServiceQueryFormDTO model = new ServiceQueryFormDTO();

    /**
     * Model tests for ServiceQueryFormDTO
     */
    @Test
    public void testServiceQueryFormDTO() {
        // TODO: test ServiceQueryFormDTO
    }

    /**
     * Test the property 'interfaceRequirements'
     */
    @Test
    public void interfaceRequirementsTest() {
        // TODO: test interfaceRequirements
    }

    /**
     * Test the property 'maxVersionRequirement'
     */
    @Test
    public void maxVersionRequirementTest() {
        // TODO: test maxVersionRequirement
    }

    /**
     * Test the property 'metadataRequirements'
     */
    @Test
    public void metadataRequirementsTest() {
        // TODO: test metadataRequirements
    }

    /**
     * Test the property 'minVersionRequirement'
     */
    @Test
    public void minVersionRequirementTest() {
        // TODO: test minVersionRequirement
    }

    /**
     * Test the property 'pingProviders'
     */
    @Test
    public void pingProvidersTest() {
        // TODO: test pingProviders
    }

    /**
     * Test the property 'providerAddressTypeRequirements'
     */
    @Test
    public void providerAddressTypeRequirementsTest() {
        // TODO: test providerAddressTypeRequirements
    }

    /**
     * Test the property 'securityRequirements'
     */
    @Test
    public void securityRequirementsTest() {
        // TODO: test securityRequirements
    }

    /**
     * Test the property 'serviceDefinitionRequirement'
     */
    @Test
    public void serviceDefinitionRequirementTest() {
        // TODO: test serviceDefinitionRequirement
    }

    /**
     * Test the property 'versionRequirement'
     */
    @Test
    public void versionRequirementTest() {
        // TODO: test versionRequirement
    }

}
