/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ServiceRegistryResponseDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceQueryResultDTO
 */
public class ServiceQueryResultDTOTest {
    private final ServiceQueryResultDTO model = new ServiceQueryResultDTO();

    /**
     * Model tests for ServiceQueryResultDTO
     */
    @Test
    public void testServiceQueryResultDTO() {
        // TODO: test ServiceQueryResultDTO
    }

    /**
     * Test the property 'serviceQueryData'
     */
    @Test
    public void serviceQueryDataTest() {
        // TODO: test serviceQueryData
    }

    /**
     * Test the property 'unfilteredHits'
     */
    @Test
    public void unfilteredHitsTest() {
        // TODO: test unfilteredHits
    }

}
