/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AutoCompleteDataResponseDTO;
import org.openapitools.client.model.ServicesGroupedByServiceDefinitionResponseDTO;
import org.openapitools.client.model.ServicesGroupedBySystemsResponseDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceRegistryGroupedResponseDTO
 */
public class ServiceRegistryGroupedResponseDTOTest {
    private final ServiceRegistryGroupedResponseDTO model = new ServiceRegistryGroupedResponseDTO();

    /**
     * Model tests for ServiceRegistryGroupedResponseDTO
     */
    @Test
    public void testServiceRegistryGroupedResponseDTO() {
        // TODO: test ServiceRegistryGroupedResponseDTO
    }

    /**
     * Test the property 'autoCompleteData'
     */
    @Test
    public void autoCompleteDataTest() {
        // TODO: test autoCompleteData
    }

    /**
     * Test the property 'servicesGroupedByServiceDefinition'
     */
    @Test
    public void servicesGroupedByServiceDefinitionTest() {
        // TODO: test servicesGroupedByServiceDefinition
    }

    /**
     * Test the property 'servicesGroupedBySystems'
     */
    @Test
    public void servicesGroupedBySystemsTest() {
        // TODO: test servicesGroupedBySystems
    }

}
