/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.SystemRequestDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceRegistryRequestDTO
 */
public class ServiceRegistryRequestDTOTest {
    private final ServiceRegistryRequestDTO model = new ServiceRegistryRequestDTO();

    /**
     * Model tests for ServiceRegistryRequestDTO
     */
    @Test
    public void testServiceRegistryRequestDTO() {
        // TODO: test ServiceRegistryRequestDTO
    }

    /**
     * Test the property 'endOfValidity'
     */
    @Test
    public void endOfValidityTest() {
        // TODO: test endOfValidity
    }

    /**
     * Test the property 'interfaces'
     */
    @Test
    public void interfacesTest() {
        // TODO: test interfaces
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'providerSystem'
     */
    @Test
    public void providerSystemTest() {
        // TODO: test providerSystem
    }

    /**
     * Test the property 'secure'
     */
    @Test
    public void secureTest() {
        // TODO: test secure
    }

    /**
     * Test the property 'serviceDefinition'
     */
    @Test
    public void serviceDefinitionTest() {
        // TODO: test serviceDefinition
    }

    /**
     * Test the property 'serviceUri'
     */
    @Test
    public void serviceUriTest() {
        // TODO: test serviceUri
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

}
