/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ServiceQueryFormDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceQueryFormListDTO
 */
public class ServiceQueryFormListDTOTest {
    private final ServiceQueryFormListDTO model = new ServiceQueryFormListDTO();

    /**
     * Model tests for ServiceQueryFormListDTO
     */
    @Test
    public void testServiceQueryFormListDTO() {
        // TODO: test ServiceQueryFormListDTO
    }

    /**
     * Test the property 'forms'
     */
    @Test
    public void formsTest() {
        // TODO: test forms
    }

}
