/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceInterfaceRequestDTO
 */
public class ServiceInterfaceRequestDTOTest {
    private final ServiceInterfaceRequestDTO model = new ServiceInterfaceRequestDTO();

    /**
     * Model tests for ServiceInterfaceRequestDTO
     */
    @Test
    public void testServiceInterfaceRequestDTO() {
        // TODO: test ServiceInterfaceRequestDTO
    }

    /**
     * Test the property 'interfaceName'
     */
    @Test
    public void interfaceNameTest() {
        // TODO: test interfaceName
    }

}
