/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ServiceRegistryResponseDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServicesGroupedByServiceDefinitionResponseDTO
 */
public class ServicesGroupedByServiceDefinitionResponseDTOTest {
    private final ServicesGroupedByServiceDefinitionResponseDTO model = new ServicesGroupedByServiceDefinitionResponseDTO();

    /**
     * Model tests for ServicesGroupedByServiceDefinitionResponseDTO
     */
    @Test
    public void testServicesGroupedByServiceDefinitionResponseDTO() {
        // TODO: test ServicesGroupedByServiceDefinitionResponseDTO
    }

    /**
     * Test the property 'providerServices'
     */
    @Test
    public void providerServicesTest() {
        // TODO: test providerServices
    }

    /**
     * Test the property 'serviceDefinition'
     */
    @Test
    public void serviceDefinitionTest() {
        // TODO: test serviceDefinition
    }

    /**
     * Test the property 'serviceDefinitionId'
     */
    @Test
    public void serviceDefinitionIdTest() {
        // TODO: test serviceDefinitionId
    }

}
