/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.KeyValuesDTO;
import org.openapitools.client.model.ServiceRegistryListResponseDTO;
import org.openapitools.client.model.SystemListResponseDTO;
import org.openapitools.client.model.SystemRequestDTO;
import org.openapitools.client.model.SystemResponseDTO;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PrivateApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PrivateApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PrivateApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getServiceRegistryEntriesBySystemIdUsingGET
     * @param id id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getServiceRegistryEntriesBySystemIdUsingGETCall(Long id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/serviceregistry/query/provider/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getServiceRegistryEntriesBySystemIdUsingGETValidateBeforeCall(Long id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getServiceRegistryEntriesBySystemIdUsingGET(Async)");
        }

        return getServiceRegistryEntriesBySystemIdUsingGETCall(id, _callback);

    }

    /**
     * Return service registry entries by system id
     * 
     * @param id id (required)
     * @return ServiceRegistryListResponseDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ServiceRegistryListResponseDTO getServiceRegistryEntriesBySystemIdUsingGET(Long id) throws ApiException {
        ApiResponse<ServiceRegistryListResponseDTO> localVarResp = getServiceRegistryEntriesBySystemIdUsingGETWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Return service registry entries by system id
     * 
     * @param id id (required)
     * @return ApiResponse&lt;ServiceRegistryListResponseDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ServiceRegistryListResponseDTO> getServiceRegistryEntriesBySystemIdUsingGETWithHttpInfo(Long id) throws ApiException {
        okhttp3.Call localVarCall = getServiceRegistryEntriesBySystemIdUsingGETValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<ServiceRegistryListResponseDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return service registry entries by system id (asynchronously)
     * 
     * @param id id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getServiceRegistryEntriesBySystemIdUsingGETAsync(Long id, final ApiCallback<ServiceRegistryListResponseDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = getServiceRegistryEntriesBySystemIdUsingGETValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<ServiceRegistryListResponseDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getServiceRegistryEntriesUsingGET1
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getServiceRegistryEntriesUsingGET1Call(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/serviceregistry/query/all";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getServiceRegistryEntriesUsingGET1ValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return getServiceRegistryEntriesUsingGET1Call(_callback);

    }

    /**
     * Return all service registry entries
     * 
     * @return ServiceRegistryListResponseDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ServiceRegistryListResponseDTO getServiceRegistryEntriesUsingGET1() throws ApiException {
        ApiResponse<ServiceRegistryListResponseDTO> localVarResp = getServiceRegistryEntriesUsingGET1WithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Return all service registry entries
     * 
     * @return ApiResponse&lt;ServiceRegistryListResponseDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ServiceRegistryListResponseDTO> getServiceRegistryEntriesUsingGET1WithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = getServiceRegistryEntriesUsingGET1ValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ServiceRegistryListResponseDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return all service registry entries (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getServiceRegistryEntriesUsingGET1Async(final ApiCallback<ServiceRegistryListResponseDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = getServiceRegistryEntriesUsingGET1ValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ServiceRegistryListResponseDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for pullConfigUsingGET
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Configuration returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call pullConfigUsingGETCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/serviceregistry/pull-config";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call pullConfigUsingGETValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return pullConfigUsingGETCall(_callback);

    }

    /**
     * Return some configuration of ServiceRegistry
     * 
     * @return KeyValuesDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Configuration returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public KeyValuesDTO pullConfigUsingGET() throws ApiException {
        ApiResponse<KeyValuesDTO> localVarResp = pullConfigUsingGETWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Return some configuration of ServiceRegistry
     * 
     * @return ApiResponse&lt;KeyValuesDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Configuration returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<KeyValuesDTO> pullConfigUsingGETWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = pullConfigUsingGETValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<KeyValuesDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return some configuration of ServiceRegistry (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Configuration returned </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call pullConfigUsingGETAsync(final ApiCallback<KeyValuesDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = pullConfigUsingGETValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<KeyValuesDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for pullSystemsUsingGET
     * @param direction direction (optional, default to ASC)
     * @param itemPerPage item_per_page (optional)
     * @param page page (optional)
     * @param sortField sort_field (optional, default to id)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Systems returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  Invalid parameters </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call pullSystemsUsingGETCall(String direction, Integer itemPerPage, Integer page, String sortField, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/serviceregistry/pull-systems";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (direction != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("direction", direction));
        }

        if (itemPerPage != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("item_per_page", itemPerPage));
        }

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (sortField != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sort_field", sortField));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call pullSystemsUsingGETValidateBeforeCall(String direction, Integer itemPerPage, Integer page, String sortField, final ApiCallback _callback) throws ApiException {
        return pullSystemsUsingGETCall(direction, itemPerPage, page, sortField, _callback);

    }

    /**
     * Return systems by request parameters
     * 
     * @param direction direction (optional, default to ASC)
     * @param itemPerPage item_per_page (optional)
     * @param page page (optional)
     * @param sortField sort_field (optional, default to id)
     * @return SystemListResponseDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Systems returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  Invalid parameters </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public SystemListResponseDTO pullSystemsUsingGET(String direction, Integer itemPerPage, Integer page, String sortField) throws ApiException {
        ApiResponse<SystemListResponseDTO> localVarResp = pullSystemsUsingGETWithHttpInfo(direction, itemPerPage, page, sortField);
        return localVarResp.getData();
    }

    /**
     * Return systems by request parameters
     * 
     * @param direction direction (optional, default to ASC)
     * @param itemPerPage item_per_page (optional)
     * @param page page (optional)
     * @param sortField sort_field (optional, default to id)
     * @return ApiResponse&lt;SystemListResponseDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Systems returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  Invalid parameters </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SystemListResponseDTO> pullSystemsUsingGETWithHttpInfo(String direction, Integer itemPerPage, Integer page, String sortField) throws ApiException {
        okhttp3.Call localVarCall = pullSystemsUsingGETValidateBeforeCall(direction, itemPerPage, page, sortField, null);
        Type localVarReturnType = new TypeToken<SystemListResponseDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return systems by request parameters (asynchronously)
     * 
     * @param direction direction (optional, default to ASC)
     * @param itemPerPage item_per_page (optional)
     * @param page page (optional)
     * @param sortField sort_field (optional, default to id)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Systems returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td>  Invalid parameters </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call pullSystemsUsingGETAsync(String direction, Integer itemPerPage, Integer page, String sortField, final ApiCallback<SystemListResponseDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = pullSystemsUsingGETValidateBeforeCall(direction, itemPerPage, page, sortField, _callback);
        Type localVarReturnType = new TypeToken<SystemListResponseDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for queryRegistryBySystemDTOUsingPOST
     * @param request request (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Consumer System data by requestDTO returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry by Consumer system requestDTO </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryRegistryBySystemDTOUsingPOSTCall(SystemRequestDTO request, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = request;

        // create path and map variables
        String localVarPath = "/serviceregistry/query/system";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call queryRegistryBySystemDTOUsingPOSTValidateBeforeCall(SystemRequestDTO request, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'request' is set
        if (request == null) {
            throw new ApiException("Missing the required parameter 'request' when calling queryRegistryBySystemDTOUsingPOST(Async)");
        }

        return queryRegistryBySystemDTOUsingPOSTCall(request, _callback);

    }

    /**
     * Return System by requested dto
     * 
     * @param request request (required)
     * @return SystemResponseDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Consumer System data by requestDTO returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry by Consumer system requestDTO </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public SystemResponseDTO queryRegistryBySystemDTOUsingPOST(SystemRequestDTO request) throws ApiException {
        ApiResponse<SystemResponseDTO> localVarResp = queryRegistryBySystemDTOUsingPOSTWithHttpInfo(request);
        return localVarResp.getData();
    }

    /**
     * Return System by requested dto
     * 
     * @param request request (required)
     * @return ApiResponse&lt;SystemResponseDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Consumer System data by requestDTO returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry by Consumer system requestDTO </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SystemResponseDTO> queryRegistryBySystemDTOUsingPOSTWithHttpInfo(SystemRequestDTO request) throws ApiException {
        okhttp3.Call localVarCall = queryRegistryBySystemDTOUsingPOSTValidateBeforeCall(request, null);
        Type localVarReturnType = new TypeToken<SystemResponseDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return System by requested dto (asynchronously)
     * 
     * @param request request (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Consumer System data by requestDTO returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry by Consumer system requestDTO </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryRegistryBySystemDTOUsingPOSTAsync(SystemRequestDTO request, final ApiCallback<SystemResponseDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = queryRegistryBySystemDTOUsingPOSTValidateBeforeCall(request, _callback);
        Type localVarReturnType = new TypeToken<SystemResponseDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for queryRegistryBySystemIdUsingGET
     * @param id id (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> System data by id returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry by Consumer system id </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryRegistryBySystemIdUsingGETCall(Long id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/serviceregistry/query/system/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call queryRegistryBySystemIdUsingGETValidateBeforeCall(Long id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling queryRegistryBySystemIdUsingGET(Async)");
        }

        return queryRegistryBySystemIdUsingGETCall(id, _callback);

    }

    /**
     * Return system by requested id
     * 
     * @param id id (required)
     * @return SystemResponseDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> System data by id returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry by Consumer system id </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public SystemResponseDTO queryRegistryBySystemIdUsingGET(Long id) throws ApiException {
        ApiResponse<SystemResponseDTO> localVarResp = queryRegistryBySystemIdUsingGETWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Return system by requested id
     * 
     * @param id id (required)
     * @return ApiResponse&lt;SystemResponseDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> System data by id returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry by Consumer system id </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SystemResponseDTO> queryRegistryBySystemIdUsingGETWithHttpInfo(Long id) throws ApiException {
        okhttp3.Call localVarCall = queryRegistryBySystemIdUsingGETValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<SystemResponseDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return system by requested id (asynchronously)
     * 
     * @param id id (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> System data by id returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry by Consumer system id </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryRegistryBySystemIdUsingGETAsync(Long id, final ApiCallback<SystemResponseDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = queryRegistryBySystemIdUsingGETValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<SystemResponseDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for queryServiceRegistryEntriesByServiceDefinitionListUsingPOST
     * @param request request (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryServiceRegistryEntriesByServiceDefinitionListUsingPOSTCall(List<String> request, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = request;

        // create path and map variables
        String localVarPath = "/serviceregistry/query/definition";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call queryServiceRegistryEntriesByServiceDefinitionListUsingPOSTValidateBeforeCall(List<String> request, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'request' is set
        if (request == null) {
            throw new ApiException("Missing the required parameter 'request' when calling queryServiceRegistryEntriesByServiceDefinitionListUsingPOST(Async)");
        }

        return queryServiceRegistryEntriesByServiceDefinitionListUsingPOSTCall(request, _callback);

    }

    /**
     * Return service registry entries by service definition list
     * 
     * @param request request (required)
     * @return ServiceRegistryListResponseDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ServiceRegistryListResponseDTO queryServiceRegistryEntriesByServiceDefinitionListUsingPOST(List<String> request) throws ApiException {
        ApiResponse<ServiceRegistryListResponseDTO> localVarResp = queryServiceRegistryEntriesByServiceDefinitionListUsingPOSTWithHttpInfo(request);
        return localVarResp.getData();
    }

    /**
     * Return service registry entries by service definition list
     * 
     * @param request request (required)
     * @return ApiResponse&lt;ServiceRegistryListResponseDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ServiceRegistryListResponseDTO> queryServiceRegistryEntriesByServiceDefinitionListUsingPOSTWithHttpInfo(List<String> request) throws ApiException {
        okhttp3.Call localVarCall = queryServiceRegistryEntriesByServiceDefinitionListUsingPOSTValidateBeforeCall(request, null);
        Type localVarReturnType = new TypeToken<ServiceRegistryListResponseDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return service registry entries by service definition list (asynchronously)
     * 
     * @param request request (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry entries returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not retrieve service registry entries </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryServiceRegistryEntriesByServiceDefinitionListUsingPOSTAsync(List<String> request, final ApiCallback<ServiceRegistryListResponseDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = queryServiceRegistryEntriesByServiceDefinitionListUsingPOSTValidateBeforeCall(request, _callback);
        Type localVarReturnType = new TypeToken<ServiceRegistryListResponseDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
