/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ServiceQueryFormDTO;
import org.openapitools.client.model.ServiceQueryFormListDTO;
import org.openapitools.client.model.ServiceQueryResultDTO;
import org.openapitools.client.model.ServiceRegistryRequestDTO;
import org.openapitools.client.model.ServiceRegistryResponseDTO;
import org.openapitools.client.model.SystemRequestDTO;
import org.openapitools.client.model.SystemResponseDTO;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ClientApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ClientApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ClientApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for echoServiceUsingGET
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Core service is available </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call echoServiceUsingGETCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/serviceregistry/echo";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call echoServiceUsingGETValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return echoServiceUsingGETCall(_callback);

    }

    /**
     * Return an echo message with the purpose of testing the core service availability
     * 
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Core service is available </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public String echoServiceUsingGET() throws ApiException {
        ApiResponse<String> localVarResp = echoServiceUsingGETWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * Return an echo message with the purpose of testing the core service availability
     * 
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Core service is available </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> echoServiceUsingGETWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = echoServiceUsingGETValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return an echo message with the purpose of testing the core service availability (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Core service is available </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call echoServiceUsingGETAsync(final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = echoServiceUsingGETValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for multiQueryRegistryUsingPOST
     * @param forms forms (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry data returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call multiQueryRegistryUsingPOSTCall(ServiceQueryFormListDTO forms, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = forms;

        // create path and map variables
        String localVarPath = "/serviceregistry/query/multi";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call multiQueryRegistryUsingPOSTValidateBeforeCall(ServiceQueryFormListDTO forms, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'forms' is set
        if (forms == null) {
            throw new ApiException("Missing the required parameter 'forms' when calling multiQueryRegistryUsingPOST(Async)");
        }

        return multiQueryRegistryUsingPOSTCall(forms, _callback);

    }

    /**
     * Return Service Registry data that fits the specification
     * 
     * @param forms forms (required)
     * @return ServiceQueryResultDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry data returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ServiceQueryResultDTO multiQueryRegistryUsingPOST(ServiceQueryFormListDTO forms) throws ApiException {
        ApiResponse<ServiceQueryResultDTO> localVarResp = multiQueryRegistryUsingPOSTWithHttpInfo(forms);
        return localVarResp.getData();
    }

    /**
     * Return Service Registry data that fits the specification
     * 
     * @param forms forms (required)
     * @return ApiResponse&lt;ServiceQueryResultDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry data returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ServiceQueryResultDTO> multiQueryRegistryUsingPOSTWithHttpInfo(ServiceQueryFormListDTO forms) throws ApiException {
        okhttp3.Call localVarCall = multiQueryRegistryUsingPOSTValidateBeforeCall(forms, null);
        Type localVarReturnType = new TypeToken<ServiceQueryResultDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return Service Registry data that fits the specification (asynchronously)
     * 
     * @param forms forms (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry data returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call multiQueryRegistryUsingPOSTAsync(ServiceQueryFormListDTO forms, final ApiCallback<ServiceQueryResultDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = multiQueryRegistryUsingPOSTValidateBeforeCall(forms, _callback);
        Type localVarReturnType = new TypeToken<ServiceQueryResultDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for queryRegistryUsingPOST
     * @param form form (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry data returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryRegistryUsingPOSTCall(ServiceQueryFormDTO form, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = form;

        // create path and map variables
        String localVarPath = "/serviceregistry/query";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call queryRegistryUsingPOSTValidateBeforeCall(ServiceQueryFormDTO form, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'form' is set
        if (form == null) {
            throw new ApiException("Missing the required parameter 'form' when calling queryRegistryUsingPOST(Async)");
        }

        return queryRegistryUsingPOSTCall(form, _callback);

    }

    /**
     * Return Service Registry data that fits the specification
     * 
     * @param form form (required)
     * @return ServiceQueryResultDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry data returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ServiceQueryResultDTO queryRegistryUsingPOST(ServiceQueryFormDTO form) throws ApiException {
        ApiResponse<ServiceQueryResultDTO> localVarResp = queryRegistryUsingPOSTWithHttpInfo(form);
        return localVarResp.getData();
    }

    /**
     * Return Service Registry data that fits the specification
     * 
     * @param form form (required)
     * @return ApiResponse&lt;ServiceQueryResultDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry data returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ServiceQueryResultDTO> queryRegistryUsingPOSTWithHttpInfo(ServiceQueryFormDTO form) throws ApiException {
        okhttp3.Call localVarCall = queryRegistryUsingPOSTValidateBeforeCall(form, null);
        Type localVarReturnType = new TypeToken<ServiceQueryResultDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return Service Registry data that fits the specification (asynchronously)
     * 
     * @param form form (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Service Registry data returned </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not query Service Registry </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call queryRegistryUsingPOSTAsync(ServiceQueryFormDTO form, final ApiCallback<ServiceQueryResultDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = queryRegistryUsingPOSTValidateBeforeCall(form, _callback);
        Type localVarReturnType = new TypeToken<ServiceQueryResultDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for registerServiceUsingPOST
     * @param dto dto (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Service registered </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not register service </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerServiceUsingPOSTCall(ServiceRegistryRequestDTO dto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = dto;

        // create path and map variables
        String localVarPath = "/serviceregistry/register";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call registerServiceUsingPOSTValidateBeforeCall(ServiceRegistryRequestDTO dto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'dto' is set
        if (dto == null) {
            throw new ApiException("Missing the required parameter 'dto' when calling registerServiceUsingPOST(Async)");
        }

        return registerServiceUsingPOSTCall(dto, _callback);

    }

    /**
     * Registers a service
     * 
     * @param dto dto (required)
     * @return ServiceRegistryResponseDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Service registered </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not register service </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ServiceRegistryResponseDTO registerServiceUsingPOST(ServiceRegistryRequestDTO dto) throws ApiException {
        ApiResponse<ServiceRegistryResponseDTO> localVarResp = registerServiceUsingPOSTWithHttpInfo(dto);
        return localVarResp.getData();
    }

    /**
     * Registers a service
     * 
     * @param dto dto (required)
     * @return ApiResponse&lt;ServiceRegistryResponseDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Service registered </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not register service </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ServiceRegistryResponseDTO> registerServiceUsingPOSTWithHttpInfo(ServiceRegistryRequestDTO dto) throws ApiException {
        okhttp3.Call localVarCall = registerServiceUsingPOSTValidateBeforeCall(dto, null);
        Type localVarReturnType = new TypeToken<ServiceRegistryResponseDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Registers a service (asynchronously)
     * 
     * @param dto dto (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> Service registered </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not register service </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerServiceUsingPOSTAsync(ServiceRegistryRequestDTO dto, final ApiCallback<ServiceRegistryResponseDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = registerServiceUsingPOSTValidateBeforeCall(dto, _callback);
        Type localVarReturnType = new TypeToken<ServiceRegistryResponseDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for registerSystemUsingPOST
     * @param dto dto (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> System created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not create system </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerSystemUsingPOSTCall(SystemRequestDTO dto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = dto;

        // create path and map variables
        String localVarPath = "/serviceregistry/register-system";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call registerSystemUsingPOSTValidateBeforeCall(SystemRequestDTO dto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'dto' is set
        if (dto == null) {
            throw new ApiException("Missing the required parameter 'dto' when calling registerSystemUsingPOST(Async)");
        }

        return registerSystemUsingPOSTCall(dto, _callback);

    }

    /**
     * Return created application system 
     * 
     * @param dto dto (required)
     * @return SystemResponseDTO
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> System created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not create system </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public SystemResponseDTO registerSystemUsingPOST(SystemRequestDTO dto) throws ApiException {
        ApiResponse<SystemResponseDTO> localVarResp = registerSystemUsingPOSTWithHttpInfo(dto);
        return localVarResp.getData();
    }

    /**
     * Return created application system 
     * 
     * @param dto dto (required)
     * @return ApiResponse&lt;SystemResponseDTO&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> System created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not create system </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SystemResponseDTO> registerSystemUsingPOSTWithHttpInfo(SystemRequestDTO dto) throws ApiException {
        okhttp3.Call localVarCall = registerSystemUsingPOSTValidateBeforeCall(dto, null);
        Type localVarReturnType = new TypeToken<SystemResponseDTO>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Return created application system  (asynchronously)
     * 
     * @param dto dto (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> System created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not create system </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call registerSystemUsingPOSTAsync(SystemRequestDTO dto, final ApiCallback<SystemResponseDTO> _callback) throws ApiException {

        okhttp3.Call localVarCall = registerSystemUsingPOSTValidateBeforeCall(dto, _callback);
        Type localVarReturnType = new TypeToken<SystemResponseDTO>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for unregisterServiceUsingDELETE
     * @param port port (required)
     * @param serviceDefinition service_definition (required)
     * @param serviceUri service_uri (required)
     * @param systemName system_name (required)
     * @param address address (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Registered service removed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not remove service </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call unregisterServiceUsingDELETECall(Integer port, String serviceDefinition, String serviceUri, String systemName, String address, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/serviceregistry/unregister";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (address != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("address", address));
        }

        if (port != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("port", port));
        }

        if (serviceDefinition != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("service_definition", serviceDefinition));
        }

        if (serviceUri != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("service_uri", serviceUri));
        }

        if (systemName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("system_name", systemName));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call unregisterServiceUsingDELETEValidateBeforeCall(Integer port, String serviceDefinition, String serviceUri, String systemName, String address, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'port' is set
        if (port == null) {
            throw new ApiException("Missing the required parameter 'port' when calling unregisterServiceUsingDELETE(Async)");
        }

        // verify the required parameter 'serviceDefinition' is set
        if (serviceDefinition == null) {
            throw new ApiException("Missing the required parameter 'serviceDefinition' when calling unregisterServiceUsingDELETE(Async)");
        }

        // verify the required parameter 'serviceUri' is set
        if (serviceUri == null) {
            throw new ApiException("Missing the required parameter 'serviceUri' when calling unregisterServiceUsingDELETE(Async)");
        }

        // verify the required parameter 'systemName' is set
        if (systemName == null) {
            throw new ApiException("Missing the required parameter 'systemName' when calling unregisterServiceUsingDELETE(Async)");
        }

        return unregisterServiceUsingDELETECall(port, serviceDefinition, serviceUri, systemName, address, _callback);

    }

    /**
     * Remove a registered service
     * 
     * @param port port (required)
     * @param serviceDefinition service_definition (required)
     * @param serviceUri service_uri (required)
     * @param systemName system_name (required)
     * @param address address (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Registered service removed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not remove service </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public void unregisterServiceUsingDELETE(Integer port, String serviceDefinition, String serviceUri, String systemName, String address) throws ApiException {
        unregisterServiceUsingDELETEWithHttpInfo(port, serviceDefinition, serviceUri, systemName, address);
    }

    /**
     * Remove a registered service
     * 
     * @param port port (required)
     * @param serviceDefinition service_definition (required)
     * @param serviceUri service_uri (required)
     * @param systemName system_name (required)
     * @param address address (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Registered service removed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not remove service </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> unregisterServiceUsingDELETEWithHttpInfo(Integer port, String serviceDefinition, String serviceUri, String systemName, String address) throws ApiException {
        okhttp3.Call localVarCall = unregisterServiceUsingDELETEValidateBeforeCall(port, serviceDefinition, serviceUri, systemName, address, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Remove a registered service (asynchronously)
     * 
     * @param port port (required)
     * @param serviceDefinition service_definition (required)
     * @param serviceUri service_uri (required)
     * @param systemName system_name (required)
     * @param address address (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Registered service removed </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not remove service </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call unregisterServiceUsingDELETEAsync(Integer port, String serviceDefinition, String serviceUri, String systemName, String address, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = unregisterServiceUsingDELETEValidateBeforeCall(port, serviceDefinition, serviceUri, systemName, address, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for unregisterSystemUsingDELETE
     * @param port port (required)
     * @param systemName system_name (required)
     * @param address address (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> System deleted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not delete system </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call unregisterSystemUsingDELETECall(Integer port, String systemName, String address, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/serviceregistry/unregister-system";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (address != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("address", address));
        }

        if (port != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("port", port));
        }

        if (systemName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("system_name", systemName));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call unregisterSystemUsingDELETEValidateBeforeCall(Integer port, String systemName, String address, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'port' is set
        if (port == null) {
            throw new ApiException("Missing the required parameter 'port' when calling unregisterSystemUsingDELETE(Async)");
        }

        // verify the required parameter 'systemName' is set
        if (systemName == null) {
            throw new ApiException("Missing the required parameter 'systemName' when calling unregisterSystemUsingDELETE(Async)");
        }

        return unregisterSystemUsingDELETECall(port, systemName, address, _callback);

    }

    /**
     * Unregister the given system
     * 
     * @param port port (required)
     * @param systemName system_name (required)
     * @param address address (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> System deleted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not delete system </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public void unregisterSystemUsingDELETE(Integer port, String systemName, String address) throws ApiException {
        unregisterSystemUsingDELETEWithHttpInfo(port, systemName, address);
    }

    /**
     * Unregister the given system
     * 
     * @param port port (required)
     * @param systemName system_name (required)
     * @param address address (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> System deleted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not delete system </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> unregisterSystemUsingDELETEWithHttpInfo(Integer port, String systemName, String address) throws ApiException {
        okhttp3.Call localVarCall = unregisterSystemUsingDELETEValidateBeforeCall(port, systemName, address, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Unregister the given system (asynchronously)
     * 
     * @param port port (required)
     * @param systemName system_name (required)
     * @param address address (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> System deleted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Could not delete system </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> You are not authorized </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> Core service is not available </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call unregisterSystemUsingDELETEAsync(Integer port, String systemName, String address, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = unregisterSystemUsingDELETEValidateBeforeCall(port, systemName, address, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
