/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.SystemRequestDTO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServiceRegistryRequestDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class ServiceRegistryRequestDTO {
  public static final String SERIALIZED_NAME_END_OF_VALIDITY = "endOfValidity";
  @SerializedName(SERIALIZED_NAME_END_OF_VALIDITY)
  private String endOfValidity;

  public static final String SERIALIZED_NAME_INTERFACES = "interfaces";
  @SerializedName(SERIALIZED_NAME_INTERFACES)
  private List<String> interfaces = new ArrayList<>();

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, String> metadata = new HashMap<>();

  public static final String SERIALIZED_NAME_PROVIDER_SYSTEM = "providerSystem";
  @SerializedName(SERIALIZED_NAME_PROVIDER_SYSTEM)
  private SystemRequestDTO providerSystem;

  public static final String SERIALIZED_NAME_SECURE = "secure";
  @SerializedName(SERIALIZED_NAME_SECURE)
  private String secure;

  public static final String SERIALIZED_NAME_SERVICE_DEFINITION = "serviceDefinition";
  @SerializedName(SERIALIZED_NAME_SERVICE_DEFINITION)
  private String serviceDefinition;

  public static final String SERIALIZED_NAME_SERVICE_URI = "serviceUri";
  @SerializedName(SERIALIZED_NAME_SERVICE_URI)
  private String serviceUri;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Integer version;

  public ServiceRegistryRequestDTO() {
  }

  public ServiceRegistryRequestDTO endOfValidity(String endOfValidity) {
    this.endOfValidity = endOfValidity;
    return this;
  }

  /**
   * Get endOfValidity
   * @return endOfValidity
   */
  @javax.annotation.Nullable
  public String getEndOfValidity() {
    return endOfValidity;
  }

  public void setEndOfValidity(String endOfValidity) {
    this.endOfValidity = endOfValidity;
  }


  public ServiceRegistryRequestDTO interfaces(List<String> interfaces) {
    this.interfaces = interfaces;
    return this;
  }

  public ServiceRegistryRequestDTO addInterfacesItem(String interfacesItem) {
    if (this.interfaces == null) {
      this.interfaces = new ArrayList<>();
    }
    this.interfaces.add(interfacesItem);
    return this;
  }

  /**
   * Get interfaces
   * @return interfaces
   */
  @javax.annotation.Nullable
  public List<String> getInterfaces() {
    return interfaces;
  }

  public void setInterfaces(List<String> interfaces) {
    this.interfaces = interfaces;
  }


  public ServiceRegistryRequestDTO metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public ServiceRegistryRequestDTO putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public ServiceRegistryRequestDTO providerSystem(SystemRequestDTO providerSystem) {
    this.providerSystem = providerSystem;
    return this;
  }

  /**
   * Get providerSystem
   * @return providerSystem
   */
  @javax.annotation.Nullable
  public SystemRequestDTO getProviderSystem() {
    return providerSystem;
  }

  public void setProviderSystem(SystemRequestDTO providerSystem) {
    this.providerSystem = providerSystem;
  }


  public ServiceRegistryRequestDTO secure(String secure) {
    this.secure = secure;
    return this;
  }

  /**
   * Get secure
   * @return secure
   */
  @javax.annotation.Nullable
  public String getSecure() {
    return secure;
  }

  public void setSecure(String secure) {
    this.secure = secure;
  }


  public ServiceRegistryRequestDTO serviceDefinition(String serviceDefinition) {
    this.serviceDefinition = serviceDefinition;
    return this;
  }

  /**
   * Get serviceDefinition
   * @return serviceDefinition
   */
  @javax.annotation.Nullable
  public String getServiceDefinition() {
    return serviceDefinition;
  }

  public void setServiceDefinition(String serviceDefinition) {
    this.serviceDefinition = serviceDefinition;
  }


  public ServiceRegistryRequestDTO serviceUri(String serviceUri) {
    this.serviceUri = serviceUri;
    return this;
  }

  /**
   * Get serviceUri
   * @return serviceUri
   */
  @javax.annotation.Nullable
  public String getServiceUri() {
    return serviceUri;
  }

  public void setServiceUri(String serviceUri) {
    this.serviceUri = serviceUri;
  }


  public ServiceRegistryRequestDTO version(Integer version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceRegistryRequestDTO serviceRegistryRequestDTO = (ServiceRegistryRequestDTO) o;
    return Objects.equals(this.endOfValidity, serviceRegistryRequestDTO.endOfValidity) &&
        Objects.equals(this.interfaces, serviceRegistryRequestDTO.interfaces) &&
        Objects.equals(this.metadata, serviceRegistryRequestDTO.metadata) &&
        Objects.equals(this.providerSystem, serviceRegistryRequestDTO.providerSystem) &&
        Objects.equals(this.secure, serviceRegistryRequestDTO.secure) &&
        Objects.equals(this.serviceDefinition, serviceRegistryRequestDTO.serviceDefinition) &&
        Objects.equals(this.serviceUri, serviceRegistryRequestDTO.serviceUri) &&
        Objects.equals(this.version, serviceRegistryRequestDTO.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endOfValidity, interfaces, metadata, providerSystem, secure, serviceDefinition, serviceUri, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceRegistryRequestDTO {\n");
    sb.append("    endOfValidity: ").append(toIndentedString(endOfValidity)).append("\n");
    sb.append("    interfaces: ").append(toIndentedString(interfaces)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    providerSystem: ").append(toIndentedString(providerSystem)).append("\n");
    sb.append("    secure: ").append(toIndentedString(secure)).append("\n");
    sb.append("    serviceDefinition: ").append(toIndentedString(serviceDefinition)).append("\n");
    sb.append("    serviceUri: ").append(toIndentedString(serviceUri)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("endOfValidity");
    openapiFields.add("interfaces");
    openapiFields.add("metadata");
    openapiFields.add("providerSystem");
    openapiFields.add("secure");
    openapiFields.add("serviceDefinition");
    openapiFields.add("serviceUri");
    openapiFields.add("version");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceRegistryRequestDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceRegistryRequestDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceRegistryRequestDTO is not found in the empty JSON string", ServiceRegistryRequestDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceRegistryRequestDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceRegistryRequestDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("endOfValidity") != null && !jsonObj.get("endOfValidity").isJsonNull()) && !jsonObj.get("endOfValidity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endOfValidity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endOfValidity").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("interfaces") != null && !jsonObj.get("interfaces").isJsonNull() && !jsonObj.get("interfaces").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `interfaces` to be an array in the JSON string but got `%s`", jsonObj.get("interfaces").toString()));
      }
      // validate the optional field `providerSystem`
      if (jsonObj.get("providerSystem") != null && !jsonObj.get("providerSystem").isJsonNull()) {
        SystemRequestDTO.validateJsonElement(jsonObj.get("providerSystem"));
      }
      if ((jsonObj.get("secure") != null && !jsonObj.get("secure").isJsonNull()) && !jsonObj.get("secure").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `secure` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secure").toString()));
      }
      if ((jsonObj.get("serviceDefinition") != null && !jsonObj.get("serviceDefinition").isJsonNull()) && !jsonObj.get("serviceDefinition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serviceDefinition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serviceDefinition").toString()));
      }
      if ((jsonObj.get("serviceUri") != null && !jsonObj.get("serviceUri").isJsonNull()) && !jsonObj.get("serviceUri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serviceUri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serviceUri").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceRegistryRequestDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceRegistryRequestDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceRegistryRequestDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceRegistryRequestDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceRegistryRequestDTO>() {
           @Override
           public void write(JsonWriter out, ServiceRegistryRequestDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceRegistryRequestDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceRegistryRequestDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceRegistryRequestDTO
   * @throws IOException if the JSON string is invalid with respect to ServiceRegistryRequestDTO
   */
  public static ServiceRegistryRequestDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceRegistryRequestDTO.class);
  }

  /**
   * Convert an instance of ServiceRegistryRequestDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

