/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ServiceRegistryResponseDTO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServicesGroupedByServiceDefinitionResponseDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class ServicesGroupedByServiceDefinitionResponseDTO {
  public static final String SERIALIZED_NAME_PROVIDER_SERVICES = "providerServices";
  @SerializedName(SERIALIZED_NAME_PROVIDER_SERVICES)
  private List<ServiceRegistryResponseDTO> providerServices = new ArrayList<>();

  public static final String SERIALIZED_NAME_SERVICE_DEFINITION = "serviceDefinition";
  @SerializedName(SERIALIZED_NAME_SERVICE_DEFINITION)
  private String serviceDefinition;

  public static final String SERIALIZED_NAME_SERVICE_DEFINITION_ID = "serviceDefinitionId";
  @SerializedName(SERIALIZED_NAME_SERVICE_DEFINITION_ID)
  private Long serviceDefinitionId;

  public ServicesGroupedByServiceDefinitionResponseDTO() {
  }

  public ServicesGroupedByServiceDefinitionResponseDTO providerServices(List<ServiceRegistryResponseDTO> providerServices) {
    this.providerServices = providerServices;
    return this;
  }

  public ServicesGroupedByServiceDefinitionResponseDTO addProviderServicesItem(ServiceRegistryResponseDTO providerServicesItem) {
    if (this.providerServices == null) {
      this.providerServices = new ArrayList<>();
    }
    this.providerServices.add(providerServicesItem);
    return this;
  }

  /**
   * Get providerServices
   * @return providerServices
   */
  @javax.annotation.Nullable
  public List<ServiceRegistryResponseDTO> getProviderServices() {
    return providerServices;
  }

  public void setProviderServices(List<ServiceRegistryResponseDTO> providerServices) {
    this.providerServices = providerServices;
  }


  public ServicesGroupedByServiceDefinitionResponseDTO serviceDefinition(String serviceDefinition) {
    this.serviceDefinition = serviceDefinition;
    return this;
  }

  /**
   * Get serviceDefinition
   * @return serviceDefinition
   */
  @javax.annotation.Nullable
  public String getServiceDefinition() {
    return serviceDefinition;
  }

  public void setServiceDefinition(String serviceDefinition) {
    this.serviceDefinition = serviceDefinition;
  }


  public ServicesGroupedByServiceDefinitionResponseDTO serviceDefinitionId(Long serviceDefinitionId) {
    this.serviceDefinitionId = serviceDefinitionId;
    return this;
  }

  /**
   * Get serviceDefinitionId
   * @return serviceDefinitionId
   */
  @javax.annotation.Nullable
  public Long getServiceDefinitionId() {
    return serviceDefinitionId;
  }

  public void setServiceDefinitionId(Long serviceDefinitionId) {
    this.serviceDefinitionId = serviceDefinitionId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicesGroupedByServiceDefinitionResponseDTO servicesGroupedByServiceDefinitionResponseDTO = (ServicesGroupedByServiceDefinitionResponseDTO) o;
    return Objects.equals(this.providerServices, servicesGroupedByServiceDefinitionResponseDTO.providerServices) &&
        Objects.equals(this.serviceDefinition, servicesGroupedByServiceDefinitionResponseDTO.serviceDefinition) &&
        Objects.equals(this.serviceDefinitionId, servicesGroupedByServiceDefinitionResponseDTO.serviceDefinitionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(providerServices, serviceDefinition, serviceDefinitionId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicesGroupedByServiceDefinitionResponseDTO {\n");
    sb.append("    providerServices: ").append(toIndentedString(providerServices)).append("\n");
    sb.append("    serviceDefinition: ").append(toIndentedString(serviceDefinition)).append("\n");
    sb.append("    serviceDefinitionId: ").append(toIndentedString(serviceDefinitionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("providerServices");
    openapiFields.add("serviceDefinition");
    openapiFields.add("serviceDefinitionId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServicesGroupedByServiceDefinitionResponseDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServicesGroupedByServiceDefinitionResponseDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServicesGroupedByServiceDefinitionResponseDTO is not found in the empty JSON string", ServicesGroupedByServiceDefinitionResponseDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServicesGroupedByServiceDefinitionResponseDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServicesGroupedByServiceDefinitionResponseDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("providerServices") != null && !jsonObj.get("providerServices").isJsonNull()) {
        JsonArray jsonArrayproviderServices = jsonObj.getAsJsonArray("providerServices");
        if (jsonArrayproviderServices != null) {
          // ensure the json data is an array
          if (!jsonObj.get("providerServices").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `providerServices` to be an array in the JSON string but got `%s`", jsonObj.get("providerServices").toString()));
          }

          // validate the optional field `providerServices` (array)
          for (int i = 0; i < jsonArrayproviderServices.size(); i++) {
            ServiceRegistryResponseDTO.validateJsonElement(jsonArrayproviderServices.get(i));
          };
        }
      }
      if ((jsonObj.get("serviceDefinition") != null && !jsonObj.get("serviceDefinition").isJsonNull()) && !jsonObj.get("serviceDefinition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serviceDefinition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serviceDefinition").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServicesGroupedByServiceDefinitionResponseDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServicesGroupedByServiceDefinitionResponseDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServicesGroupedByServiceDefinitionResponseDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServicesGroupedByServiceDefinitionResponseDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<ServicesGroupedByServiceDefinitionResponseDTO>() {
           @Override
           public void write(JsonWriter out, ServicesGroupedByServiceDefinitionResponseDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServicesGroupedByServiceDefinitionResponseDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServicesGroupedByServiceDefinitionResponseDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServicesGroupedByServiceDefinitionResponseDTO
   * @throws IOException if the JSON string is invalid with respect to ServicesGroupedByServiceDefinitionResponseDTO
   */
  public static ServicesGroupedByServiceDefinitionResponseDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServicesGroupedByServiceDefinitionResponseDTO.class);
  }

  /**
   * Convert an instance of ServicesGroupedByServiceDefinitionResponseDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

