/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ServiceRegistryResponseDTO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServiceQueryResultDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class ServiceQueryResultDTO {
  public static final String SERIALIZED_NAME_SERVICE_QUERY_DATA = "serviceQueryData";
  @SerializedName(SERIALIZED_NAME_SERVICE_QUERY_DATA)
  private List<ServiceRegistryResponseDTO> serviceQueryData = new ArrayList<>();

  public static final String SERIALIZED_NAME_UNFILTERED_HITS = "unfilteredHits";
  @SerializedName(SERIALIZED_NAME_UNFILTERED_HITS)
  private Integer unfilteredHits;

  public ServiceQueryResultDTO() {
  }

  public ServiceQueryResultDTO serviceQueryData(List<ServiceRegistryResponseDTO> serviceQueryData) {
    this.serviceQueryData = serviceQueryData;
    return this;
  }

  public ServiceQueryResultDTO addServiceQueryDataItem(ServiceRegistryResponseDTO serviceQueryDataItem) {
    if (this.serviceQueryData == null) {
      this.serviceQueryData = new ArrayList<>();
    }
    this.serviceQueryData.add(serviceQueryDataItem);
    return this;
  }

  /**
   * Get serviceQueryData
   * @return serviceQueryData
   */
  @javax.annotation.Nullable
  public List<ServiceRegistryResponseDTO> getServiceQueryData() {
    return serviceQueryData;
  }

  public void setServiceQueryData(List<ServiceRegistryResponseDTO> serviceQueryData) {
    this.serviceQueryData = serviceQueryData;
  }


  public ServiceQueryResultDTO unfilteredHits(Integer unfilteredHits) {
    this.unfilteredHits = unfilteredHits;
    return this;
  }

  /**
   * Get unfilteredHits
   * @return unfilteredHits
   */
  @javax.annotation.Nullable
  public Integer getUnfilteredHits() {
    return unfilteredHits;
  }

  public void setUnfilteredHits(Integer unfilteredHits) {
    this.unfilteredHits = unfilteredHits;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceQueryResultDTO serviceQueryResultDTO = (ServiceQueryResultDTO) o;
    return Objects.equals(this.serviceQueryData, serviceQueryResultDTO.serviceQueryData) &&
        Objects.equals(this.unfilteredHits, serviceQueryResultDTO.unfilteredHits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceQueryData, unfilteredHits);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceQueryResultDTO {\n");
    sb.append("    serviceQueryData: ").append(toIndentedString(serviceQueryData)).append("\n");
    sb.append("    unfilteredHits: ").append(toIndentedString(unfilteredHits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("serviceQueryData");
    openapiFields.add("unfilteredHits");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceQueryResultDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceQueryResultDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceQueryResultDTO is not found in the empty JSON string", ServiceQueryResultDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceQueryResultDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceQueryResultDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("serviceQueryData") != null && !jsonObj.get("serviceQueryData").isJsonNull()) {
        JsonArray jsonArrayserviceQueryData = jsonObj.getAsJsonArray("serviceQueryData");
        if (jsonArrayserviceQueryData != null) {
          // ensure the json data is an array
          if (!jsonObj.get("serviceQueryData").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `serviceQueryData` to be an array in the JSON string but got `%s`", jsonObj.get("serviceQueryData").toString()));
          }

          // validate the optional field `serviceQueryData` (array)
          for (int i = 0; i < jsonArrayserviceQueryData.size(); i++) {
            ServiceRegistryResponseDTO.validateJsonElement(jsonArrayserviceQueryData.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceQueryResultDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceQueryResultDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceQueryResultDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceQueryResultDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceQueryResultDTO>() {
           @Override
           public void write(JsonWriter out, ServiceQueryResultDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceQueryResultDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceQueryResultDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceQueryResultDTO
   * @throws IOException if the JSON string is invalid with respect to ServiceQueryResultDTO
   */
  public static ServiceQueryResultDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceQueryResultDTO.class);
  }

  /**
   * Convert an instance of ServiceQueryResultDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

