/*
 * Arrowhead Service Registry Core System API
 * This page shows the REST interfaces offered by the Service Registry Core System.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ServiceDefinitionResponseDTO;
import org.openapitools.client.model.ServiceInterfaceResponseDTO;
import org.openapitools.client.model.SystemResponseDTO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServiceRegistryResponseDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class ServiceRegistryResponseDTO {
  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_END_OF_VALIDITY = "endOfValidity";
  @SerializedName(SERIALIZED_NAME_END_OF_VALIDITY)
  private String endOfValidity;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_INTERFACES = "interfaces";
  @SerializedName(SERIALIZED_NAME_INTERFACES)
  private List<ServiceInterfaceResponseDTO> interfaces = new ArrayList<>();

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, String> metadata = new HashMap<>();

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  private SystemResponseDTO provider;

  /**
   * Gets or Sets secure
   */
  @JsonAdapter(SecureEnum.Adapter.class)
  public enum SecureEnum {
    NOT_SECURE("NOT_SECURE"),
    
    CERTIFICATE("CERTIFICATE"),
    
    TOKEN("TOKEN");

    private String value;

    SecureEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SecureEnum fromValue(String value) {
      for (SecureEnum b : SecureEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SecureEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SecureEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SecureEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SecureEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      SecureEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SECURE = "secure";
  @SerializedName(SERIALIZED_NAME_SECURE)
  private SecureEnum secure;

  public static final String SERIALIZED_NAME_SERVICE_DEFINITION = "serviceDefinition";
  @SerializedName(SERIALIZED_NAME_SERVICE_DEFINITION)
  private ServiceDefinitionResponseDTO serviceDefinition;

  public static final String SERIALIZED_NAME_SERVICE_URI = "serviceUri";
  @SerializedName(SERIALIZED_NAME_SERVICE_URI)
  private String serviceUri;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Integer version;

  public ServiceRegistryResponseDTO() {
  }

  public ServiceRegistryResponseDTO createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public ServiceRegistryResponseDTO endOfValidity(String endOfValidity) {
    this.endOfValidity = endOfValidity;
    return this;
  }

  /**
   * Get endOfValidity
   * @return endOfValidity
   */
  @javax.annotation.Nullable
  public String getEndOfValidity() {
    return endOfValidity;
  }

  public void setEndOfValidity(String endOfValidity) {
    this.endOfValidity = endOfValidity;
  }


  public ServiceRegistryResponseDTO id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  public ServiceRegistryResponseDTO interfaces(List<ServiceInterfaceResponseDTO> interfaces) {
    this.interfaces = interfaces;
    return this;
  }

  public ServiceRegistryResponseDTO addInterfacesItem(ServiceInterfaceResponseDTO interfacesItem) {
    if (this.interfaces == null) {
      this.interfaces = new ArrayList<>();
    }
    this.interfaces.add(interfacesItem);
    return this;
  }

  /**
   * Get interfaces
   * @return interfaces
   */
  @javax.annotation.Nullable
  public List<ServiceInterfaceResponseDTO> getInterfaces() {
    return interfaces;
  }

  public void setInterfaces(List<ServiceInterfaceResponseDTO> interfaces) {
    this.interfaces = interfaces;
  }


  public ServiceRegistryResponseDTO metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public ServiceRegistryResponseDTO putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public ServiceRegistryResponseDTO provider(SystemResponseDTO provider) {
    this.provider = provider;
    return this;
  }

  /**
   * Get provider
   * @return provider
   */
  @javax.annotation.Nullable
  public SystemResponseDTO getProvider() {
    return provider;
  }

  public void setProvider(SystemResponseDTO provider) {
    this.provider = provider;
  }


  public ServiceRegistryResponseDTO secure(SecureEnum secure) {
    this.secure = secure;
    return this;
  }

  /**
   * Get secure
   * @return secure
   */
  @javax.annotation.Nullable
  public SecureEnum getSecure() {
    return secure;
  }

  public void setSecure(SecureEnum secure) {
    this.secure = secure;
  }


  public ServiceRegistryResponseDTO serviceDefinition(ServiceDefinitionResponseDTO serviceDefinition) {
    this.serviceDefinition = serviceDefinition;
    return this;
  }

  /**
   * Get serviceDefinition
   * @return serviceDefinition
   */
  @javax.annotation.Nullable
  public ServiceDefinitionResponseDTO getServiceDefinition() {
    return serviceDefinition;
  }

  public void setServiceDefinition(ServiceDefinitionResponseDTO serviceDefinition) {
    this.serviceDefinition = serviceDefinition;
  }


  public ServiceRegistryResponseDTO serviceUri(String serviceUri) {
    this.serviceUri = serviceUri;
    return this;
  }

  /**
   * Get serviceUri
   * @return serviceUri
   */
  @javax.annotation.Nullable
  public String getServiceUri() {
    return serviceUri;
  }

  public void setServiceUri(String serviceUri) {
    this.serviceUri = serviceUri;
  }


  public ServiceRegistryResponseDTO updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ServiceRegistryResponseDTO version(Integer version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceRegistryResponseDTO serviceRegistryResponseDTO = (ServiceRegistryResponseDTO) o;
    return Objects.equals(this.createdAt, serviceRegistryResponseDTO.createdAt) &&
        Objects.equals(this.endOfValidity, serviceRegistryResponseDTO.endOfValidity) &&
        Objects.equals(this.id, serviceRegistryResponseDTO.id) &&
        Objects.equals(this.interfaces, serviceRegistryResponseDTO.interfaces) &&
        Objects.equals(this.metadata, serviceRegistryResponseDTO.metadata) &&
        Objects.equals(this.provider, serviceRegistryResponseDTO.provider) &&
        Objects.equals(this.secure, serviceRegistryResponseDTO.secure) &&
        Objects.equals(this.serviceDefinition, serviceRegistryResponseDTO.serviceDefinition) &&
        Objects.equals(this.serviceUri, serviceRegistryResponseDTO.serviceUri) &&
        Objects.equals(this.updatedAt, serviceRegistryResponseDTO.updatedAt) &&
        Objects.equals(this.version, serviceRegistryResponseDTO.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, endOfValidity, id, interfaces, metadata, provider, secure, serviceDefinition, serviceUri, updatedAt, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceRegistryResponseDTO {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    endOfValidity: ").append(toIndentedString(endOfValidity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    interfaces: ").append(toIndentedString(interfaces)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    secure: ").append(toIndentedString(secure)).append("\n");
    sb.append("    serviceDefinition: ").append(toIndentedString(serviceDefinition)).append("\n");
    sb.append("    serviceUri: ").append(toIndentedString(serviceUri)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("createdAt");
    openapiFields.add("endOfValidity");
    openapiFields.add("id");
    openapiFields.add("interfaces");
    openapiFields.add("metadata");
    openapiFields.add("provider");
    openapiFields.add("secure");
    openapiFields.add("serviceDefinition");
    openapiFields.add("serviceUri");
    openapiFields.add("updatedAt");
    openapiFields.add("version");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceRegistryResponseDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceRegistryResponseDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceRegistryResponseDTO is not found in the empty JSON string", ServiceRegistryResponseDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceRegistryResponseDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceRegistryResponseDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("createdAt") != null && !jsonObj.get("createdAt").isJsonNull()) && !jsonObj.get("createdAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createdAt").toString()));
      }
      if ((jsonObj.get("endOfValidity") != null && !jsonObj.get("endOfValidity").isJsonNull()) && !jsonObj.get("endOfValidity").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endOfValidity` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endOfValidity").toString()));
      }
      if (jsonObj.get("interfaces") != null && !jsonObj.get("interfaces").isJsonNull()) {
        JsonArray jsonArrayinterfaces = jsonObj.getAsJsonArray("interfaces");
        if (jsonArrayinterfaces != null) {
          // ensure the json data is an array
          if (!jsonObj.get("interfaces").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `interfaces` to be an array in the JSON string but got `%s`", jsonObj.get("interfaces").toString()));
          }

          // validate the optional field `interfaces` (array)
          for (int i = 0; i < jsonArrayinterfaces.size(); i++) {
            ServiceInterfaceResponseDTO.validateJsonElement(jsonArrayinterfaces.get(i));
          };
        }
      }
      // validate the optional field `provider`
      if (jsonObj.get("provider") != null && !jsonObj.get("provider").isJsonNull()) {
        SystemResponseDTO.validateJsonElement(jsonObj.get("provider"));
      }
      if ((jsonObj.get("secure") != null && !jsonObj.get("secure").isJsonNull()) && !jsonObj.get("secure").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `secure` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secure").toString()));
      }
      // validate the optional field `secure`
      if (jsonObj.get("secure") != null && !jsonObj.get("secure").isJsonNull()) {
        SecureEnum.validateJsonElement(jsonObj.get("secure"));
      }
      // validate the optional field `serviceDefinition`
      if (jsonObj.get("serviceDefinition") != null && !jsonObj.get("serviceDefinition").isJsonNull()) {
        ServiceDefinitionResponseDTO.validateJsonElement(jsonObj.get("serviceDefinition"));
      }
      if ((jsonObj.get("serviceUri") != null && !jsonObj.get("serviceUri").isJsonNull()) && !jsonObj.get("serviceUri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `serviceUri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("serviceUri").toString()));
      }
      if ((jsonObj.get("updatedAt") != null && !jsonObj.get("updatedAt").isJsonNull()) && !jsonObj.get("updatedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `updatedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("updatedAt").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceRegistryResponseDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceRegistryResponseDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceRegistryResponseDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceRegistryResponseDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceRegistryResponseDTO>() {
           @Override
           public void write(JsonWriter out, ServiceRegistryResponseDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceRegistryResponseDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceRegistryResponseDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceRegistryResponseDTO
   * @throws IOException if the JSON string is invalid with respect to ServiceRegistryResponseDTO
   */
  public static ServiceRegistryResponseDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceRegistryResponseDTO.class);
  }

  /**
   * Convert an instance of ServiceRegistryResponseDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

